$axure.loadCurrentPage({
  "url":"risks.html",
  "generationDate":new Date(1520018787692.93),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"85accf1fd773455ba3f32f2e65478481",
    "type":"Axure:Page",
    "name":"Risks",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"3b3341b0ce12477bb5fbe572bc091b73",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"4bf034ee21ba4a9c88f41f4b11a279dd"},
{
          "id":"2b44143ea65c42f2af56f14803beadd0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF3399CC},
            "location":{
              "x":151,
              "y":117},
            "size":{
              "width":2050,
              "height":1530}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"86a99fef77ad4af184da041f5fecd840",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF3399CC},
                "location":{
                  "x":151,
                  "y":117},
                "size":{
                  "width":2050,
                  "height":1530}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/create_plan/u5.png"}},
{
          "id":"9910920ce07d4698920868399b5a1762",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":210,
              "y":499},
            "size":{
              "width":1930,
              "height":1091}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5d04512715704306a6df62cc6ba0d3ba",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":210,
                  "y":499},
                "size":{
                  "width":1930,
                  "height":1091}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/create_plan/u7.png"}},
{
          "id":"df456e10d80a47888b17e5ad4825b458",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"48px",
            "location":{
              "x":610,
              "y":560},
            "size":{
              "width":399,
              "height":55}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f6ecf526d0dd41d1851c40bdc2954c41",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"48px",
                "location":{
                  "x":610,
                  "y":560},
                "size":{
                  "width":399,
                  "height":55}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8e98ab5591bd4232bfe9d79b2d98d201",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"72px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":778,
              "y":188},
            "size":{
              "width":797,
              "height":82},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"91b1a83ac46b4fcabb5c65b2fabd0601",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"72px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":778,
                  "y":188},
                "size":{
                  "width":797,
                  "height":82},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0871f300eee4411db15503df3bdd9a7f",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFF00FF99},
{
                  "color":0xFF00FF99},
{
                  "color":0xFFE4E4E4},
{
                  "color":0xFFE4E4E4}]},
            "location":{
              "x":230,
              "y":349},
            "size":{
              "width":110,
              "height":110}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dd8db6965f84441f9cadba19a629ad43",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFF00FF99},
{
                      "color":0xFF00FF99},
{
                      "color":0xFFE4E4E4},
{
                      "color":0xFFE4E4E4}]},
                "location":{
                  "x":230,
                  "y":349},
                "size":{
                  "width":110,
                  "height":110}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Create Plan in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"create_plan.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/monitor_kpis/u13.png"}},
{
          "id":"a0c382b5d98347748e24d6dc3b9498b6",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":276,
              "y":386},
            "size":{
              "width":19,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d9cc2189d01f44b88ac4444373ad1bd9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":276,
                  "y":386},
                "size":{
                  "width":19,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c25a1d084af74eff9f904de644ea00cc",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFF3BF8AC},
{
                  "color":0xFF3BF8AC},
{
                  "color":0xFFE4E4E4},
{
                  "color":0xFFE4E4E4}]},
            "location":{
              "x":615,
              "y":349},
            "size":{
              "width":110,
              "height":110}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f4ba4af9bf7844dcb49a2fc25251ed90",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFF3BF8AC},
{
                      "color":0xFF3BF8AC},
{
                      "color":0xFFE4E4E4},
{
                      "color":0xFFE4E4E4}]},
                "location":{
                  "x":615,
                  "y":349},
                "size":{
                  "width":110,
                  "height":110}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Monitor KPIs in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"monitor_kpis.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/create_plan/u15.png"}},
{
          "id":"b8e595d3603447b0ada2a0ba292e3c92",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":661,
              "y":386},
            "size":{
              "width":19,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0806f54a49c44af1abc3c4129dcd0f1e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":661,
                  "y":386},
                "size":{
                  "width":19,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f3c162ecb6584006b7d18006e83042d7",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFF3BF8AC},
{
                  "color":0xFF3BF8AC},
{
                  "color":0xFFE4E4E4},
{
                  "color":0xFFE4E4E4}]},
            "location":{
              "x":1027,
              "y":349},
            "size":{
              "width":110,
              "height":110}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"327b6e61a8364a6aa1d5989e290ff208",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFF3BF8AC},
{
                      "color":0xFF3BF8AC},
{
                      "color":0xFFE4E4E4},
{
                      "color":0xFFE4E4E4}]},
                "location":{
                  "x":1027,
                  "y":349},
                "size":{
                  "width":110,
                  "height":110}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/create_plan/u15.png"}},
{
          "id":"2f51c3927d7243e78947d12aef9ac12a",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":1073,
              "y":386},
            "size":{
              "width":19,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"68e67fad1c91427eb64ce4841c19ab46",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1073,
                  "y":386},
                "size":{
                  "width":19,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d4de9fbd5cc743b982797ede8221a007",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":1416,
              "y":349},
            "size":{
              "width":110,
              "height":110}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f672408c4ad44c02b553c188cf88a5b7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1416,
                  "y":349},
                "size":{
                  "width":110,
                  "height":110}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/create_plan/u19.png"}},
{
          "id":"34643e800fd04a0cbedfc32dfe31ab59",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":1462,
              "y":386},
            "size":{
              "width":19,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f8a4367eed254fdfa81a1af7990b01d5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1462,
                  "y":386},
                "size":{
                  "width":19,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4dde4683ff9d4973a7b5b2d0011c4282",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":1759,
              "y":349},
            "size":{
              "width":110,
              "height":110}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7c9aea263ca8485285424faf5b67fcfc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1759,
                  "y":349},
                "size":{
                  "width":110,
                  "height":110}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/create_plan/u19.png"}},
{
          "id":"45dbbd1fddbc44c1a0d4b1d0087e6ce3",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":1805,
              "y":386},
            "size":{
              "width":19,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7146b9d709e44dc88297ce42b8bb9575",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1805,
                  "y":386},
                "size":{
                  "width":19,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"85a6806ba80e48e7966881ea5f229333",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":2027,
              "y":349},
            "size":{
              "width":110,
              "height":110}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5f395e468b1948bba45b3bfd85dd8d6e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":2027,
                  "y":349},
                "size":{
                  "width":110,
                  "height":110}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/create_plan/u19.png"}},
{
          "id":"4672a4df58ad415c951ab6eb9e6d45fb",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":2073,
              "y":386},
            "size":{
              "width":19,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4fbe66a8dd59480ca50873e9a3eabf90",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":2073,
                  "y":386},
                "size":{
                  "width":19,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9645b5cff75e4bad81e4ed8dbca48498",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"48px",
            "fill":{
              "fillType":"solid",
              "color":0xFF00CC99},
            "location":{
              "x":1892,
              "y":1410},
            "size":{
              "width":248,
              "height":180},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e44f27d8aec8462899f411b8fc84a74c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"48px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF00CC99},
                "location":{
                  "x":1892,
                  "y":1410},
                "size":{
                  "width":248,
                  "height":180},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Capabilities in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"capabilities.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/create_plan/u48.png"}},
{
          "id":"a3bb3938704f4953a1ed0d7c2df328ef",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"48px",
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":1360,
              "y":939},
            "size":{
              "width":248,
              "height":271},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e3b34b0033834f368776bf771ce3b866",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"48px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":1360,
                  "y":939},
                "size":{
                  "width":248,
                  "height":271},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/risks/u39.png"}},
{
          "id":"3844c01aae414cfc9b7d73ac79748c66",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":276,
              "y":661},
            "size":{
              "width":1814,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1bb4674967584d2aadc94148383e3740",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":276,
                  "y":661},
                "size":{
                  "width":1814,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/risks/u41.png"}},
{
          "id":"8579c9dff0174feb9706b9fac426274c",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"36px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":325,
              "y":691},
            "size":{
              "width":184,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"360958bab1784c988bdc98db4a861c69",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"36px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":325,
                  "y":691},
                "size":{
                  "width":184,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fe01ab9294a4463c93613ea642117ea0",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"36px",
            "location":{
              "x":276,
              "y":790},
            "size":{
              "width":141,
              "height":41}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a839af92aadd4a9ca40e54b498a354da",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"36px",
                "location":{
                  "x":276,
                  "y":790},
                "size":{
                  "width":141,
                  "height":41}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"99a901b597f74e92bfd33790bc5fe710",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":430,
              "y":790},
            "size":{
              "width":600,
              "height":41}},
          "adaptiveStyles":{
}},
{
          "id":"134b66578ece4f13b5b1af42ecadffec",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":276,
              "y":1248},
            "size":{
              "width":1544,
              "height":280}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e7cc29adaf0f496e89df8c8a37a6824c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":276,
                  "y":1248},
                "size":{
                  "width":1544,
                  "height":280}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/risks/u48.png"}},
{
          "id":"f310e6989dc74237a4835f90c01f5b25",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":325,
              "y":1278},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setPanelState",
                      "description":"Set (Dynamic Panel) to State2 fade out 500ms fade in 500ms",
                      "panelsToStates":[{
                          "panelPath":["f310e6989dc74237a4835f90c01f5b25"],
                          "stateInfo":{
                            "setStateType":"diagram",
                            "stateNumber":2,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":false,
                            "showWhenSet":false,
                            "options":{
                              "animateOut":{
                                "easing":"fade",
                                "duration":500},
                              "animateIn":{
                                "easing":"fade",
                                "duration":500},
                              "compress":false}}}]}]}]}},
          "tabbable":true,
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":true,
          "diagrams":[{
              "id":"da865e8c0a424b4c89acb9f0c049d97f",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"f03cb35631a94360928d669a114b90e4",
                  "label":"",
                  "parentDynamicPanel":"f310e6989dc74237a4835f90c01f5b25",
                  "panelIndex":0,
                  "type":"flowShape",
                  "styleType":"flowShape",
                  "visible":true,
                  "style":{
                    "fontSize":"28px",
                    "horizontalAlignment":"left",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFF0000},
                    "size":{
                      "width":265,
                      "height":60}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"62f72b52862f4c53a99595f972379fd6",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f310e6989dc74237a4835f90c01f5b25",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"28px",
                        "horizontalAlignment":"left",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFF0000},
                        "size":{
                          "width":265,
                          "height":60}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/risks/u51.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}},
{
              "id":"9a808ec4f8ae43dc90f517cc42421a1a",
              "label":"State2",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"7a1687d5806147fa8012905a5a3e70a6",
                  "label":"",
                  "parentDynamicPanel":"f310e6989dc74237a4835f90c01f5b25",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":230,
                      "y":135},
                    "size":{
                      "width":510,
                      "height":315}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"cd474d3c4a94443c8652180bdecff6c1",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f310e6989dc74237a4835f90c01f5b25",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":230,
                          "y":135},
                        "size":{
                          "width":510,
                          "height":315}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/risks/u53.png"}},
{
                  "id":"a0d5e8def4404d4a9ea6f6c151dcbd68",
                  "label":"",
                  "parentDynamicPanel":"f310e6989dc74237a4835f90c01f5b25",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"h1",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":250,
                      "y":153},
                    "size":{
                      "width":95,
                      "height":37}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"040fad864f6c491bb8a4773ac96dc0c4",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f310e6989dc74237a4835f90c01f5b25",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":250,
                          "y":153},
                        "size":{
                          "width":95,
                          "height":37}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"db18391362e14af9b5a00e63e38ebca1",
                  "label":"",
                  "parentDynamicPanel":"f310e6989dc74237a4835f90c01f5b25",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":250,
                      "y":218},
                    "size":{
                      "width":380,
                      "height":91}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"2c462d20c08c421db158590ad8e374d3",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f310e6989dc74237a4835f90c01f5b25",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":250,
                          "y":218},
                        "size":{
                          "width":380,
                          "height":91}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"1203f23aa22a45569c4b24c68af98ea7",
                  "label":"",
                  "parentDynamicPanel":"f310e6989dc74237a4835f90c01f5b25",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"h1",
                  "visible":true,
                  "style":{
                    "fontSize":"18px",
                    "location":{
                      "x":250,
                      "y":391},
                    "size":{
                      "width":52,
                      "height":22}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"1ed3f596d4e646d79d7b9d84ff058c27",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f310e6989dc74237a4835f90c01f5b25",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"18px",
                        "location":{
                          "x":250,
                          "y":391},
                        "size":{
                          "width":52,
                          "height":22}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"Set (Dynamic Panel) to State1",
                              "panelsToStates":[{
                                  "panelPath":["f310e6989dc74237a4835f90c01f5b25"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":1,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"896903fbb80148f0ad0f05aa115bd000",
                  "label":"",
                  "parentDynamicPanel":"f310e6989dc74237a4835f90c01f5b25",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"h2",
                  "visible":true,
                  "style":{
                    "fontSize":"20px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFCC0000,
                      "opacity":1},
                    "location":{
                      "x":639,
                      "y":161},
                    "size":{
                      "width":68,
                      "height":23}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c2e99c28b734447ca72097669e184b4b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f310e6989dc74237a4835f90c01f5b25",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"20px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFCC0000,
                          "opacity":1},
                        "location":{
                          "x":639,
                          "y":161},
                        "size":{
                          "width":68,
                          "height":23}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"9fb50431a7fe41de9f13b75fa3782ca4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":532,
              "y":1302},
            "size":{
              "width":43,
              "height":43}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6c114b1b5ef44c24b9796296abe676b0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":532,
                  "y":1302},
                "size":{
                  "width":43,
                  "height":43}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/create_plan/u9.png"}},
{
          "id":"52396f85b4844e1eadf49f7ae5040b96",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":470,
              "y":1303},
            "size":{
              "width":42,
              "height":42},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCC0033}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"077d8a6fd1724fb9b36fcb31d1c83b0f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":470,
                  "y":1303},
                "size":{
                  "width":42,
                  "height":42},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCC0033}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/create_plan/u69.png"}},
{
          "id":"eb49d1b59ff841a999512edea8473c64",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":470,
              "y":1337},
            "size":{
              "width":100,
              "height":13},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8b771a795a2e42dbabe5bfa68b8a560b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":470,
                  "y":1337},
                "size":{
                  "width":100,
                  "height":13},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/create_plan/u71.png"}},
{
          "id":"e12697d5027745ba84f3a0806632cebb",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "horizontalAlignment":"left",
            "fill":{
              "fillType":"solid",
              "color":0xFFCC9900},
            "location":{
              "x":637,
              "y":1278},
            "size":{
              "width":265,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5ab3a0151f2f438292d66cac8915bea2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "horizontalAlignment":"left",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCC9900},
                "location":{
                  "x":637,
                  "y":1278},
                "size":{
                  "width":265,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/risks/u69.png"}},
{
          "id":"dc2310bb9a584c46b8b4cde4a131ce11",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":844,
              "y":1302},
            "size":{
              "width":43,
              "height":43}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"93e662b319fc470db9f448ef30d81ddd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":844,
                  "y":1302},
                "size":{
                  "width":43,
                  "height":43}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/create_plan/u9.png"}},
{
          "id":"d6171ed212d2487ea5722e51aeb2e69b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":782,
              "y":1303},
            "size":{
              "width":42,
              "height":42},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCC0033}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"65d6ab469f5f48adb320a92e0c51627d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":782,
                  "y":1303},
                "size":{
                  "width":42,
                  "height":42},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCC0033}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/create_plan/u69.png"}},
{
          "id":"17c572e2f7ca453d933c96735c0138f4",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":782,
              "y":1337},
            "size":{
              "width":100,
              "height":13},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"78bd03a41b7241358ce4697a20fe17ac",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":782,
                  "y":1337},
                "size":{
                  "width":100,
                  "height":13},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/create_plan/u71.png"}},
{
          "id":"da846085048b4324bf5374dc32a201f2",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "horizontalAlignment":"left",
            "fill":{
              "fillType":"solid",
              "color":0xFFCCFF00},
            "location":{
              "x":941,
              "y":1278},
            "size":{
              "width":265,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d056ec2a622c46cb9cbf4526f3769aad",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "horizontalAlignment":"left",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCFF00},
                "location":{
                  "x":941,
                  "y":1278},
                "size":{
                  "width":265,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/risks/u77.png"}},
{
          "id":"b354c62f7e114dda9d2fab599dcd9ca9",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1148,
              "y":1302},
            "size":{
              "width":43,
              "height":43}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0f6783be79d144eea73608d0ce8880a9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1148,
                  "y":1302},
                "size":{
                  "width":43,
                  "height":43}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/create_plan/u9.png"}},
{
          "id":"afe1e308b3ed439484978abc85daf64d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1086,
              "y":1303},
            "size":{
              "width":42,
              "height":42},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCC0033}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aa672bbb39c44aebb5f42d9af80c390e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1086,
                  "y":1303},
                "size":{
                  "width":42,
                  "height":42},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCC0033}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/create_plan/u69.png"}},
{
          "id":"7b1def5bd84c4653992266e73834acce",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":1086,
              "y":1337},
            "size":{
              "width":100,
              "height":13},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c2e5c3850902473486a6529a995a37a7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":1086,
                  "y":1337},
                "size":{
                  "width":100,
                  "height":13},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/create_plan/u71.png"}},
{
          "id":"1f8373d2d2134fafa0a4380ffe760ac2",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"36px",
            "location":{
              "x":276,
              "y":879},
            "size":{
              "width":197,
              "height":41}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1f107506025848bc902e81c4ef166a53",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"36px",
                "location":{
                  "x":276,
                  "y":879},
                "size":{
                  "width":197,
                  "height":41}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3f54013c4b6841ef88e6a21d96c02de9",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":276,
              "y":939},
            "size":{
              "width":970,
              "height":271}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a784848cf27a46cab91de50d9d5cf80a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":276,
                  "y":939},
                "size":{
                  "width":970,
                  "height":271}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/risks/u87.png"}},
{
          "id":"3ea70d23b03248a3a5150734fa9db815",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"bb2271a413fd44b882b5f8b1ed36926a"}]}},
  "masters":{
    "4bf034ee21ba4a9c88f41f4b11a279dd":{
      "packageId":"4bf034ee21ba4a9c88f41f4b11a279dd",
      "type":"Axure:Master",
      "name":"ipad",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"b7fd228ad5a240279ab302aee1b87b52",
            "label":"",
            "type":"flowShape",
            "styleType":"flowShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF333333},
              "size":{
                "width":2352,
                "height":1764},
              "borderFill":{
                "fillType":"linearGradient",
                "colors":[{
                    "color":0xFF000099},
{
                    "color":0xFF000099},
{
                    "color":0xFF000000},
{
                    "color":0xFF000000}]}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"2bfa5c8614094fb287d60d7d12e45ee2",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF333333},
                  "size":{
                    "width":2352,
                    "height":1764},
                  "borderFill":{
                    "fillType":"linearGradient",
                    "colors":[{
                        "color":0xFF000099},
{
                        "color":0xFF000099},
{
                        "color":0xFF000000},
{
                        "color":0xFF000000}]}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/low_fi_index/u1.png"}},
{
            "id":"fc15c73249d34b269969db2b09f4acef",
            "label":"",
            "type":"flowShape",
            "styleType":"flowShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"linearGradient",
                "colors":[{
                    "color":0xFFFFFFFF},
{
                    "color":0xFFFFFFFF},
{
                    "color":0xFFE4E4E4},
{
                    "color":0xFFE4E4E4}]},
              "location":{
                "x":152,
                "y":114},
              "size":{
                "width":2048,
                "height":1536}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"4bb6471cc35846dab73c365841f3ef41",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"linearGradient",
                    "colors":[{
                        "color":0xFFFFFFFF},
{
                        "color":0xFFFFFFFF},
{
                        "color":0xFFE4E4E4},
{
                        "color":0xFFE4E4E4}]},
                  "location":{
                    "x":152,
                    "y":114},
                  "size":{
                    "width":2048,
                    "height":1536}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/low_fi_index/u3.png"}}]}},
    "bb2271a413fd44b882b5f8b1ed36926a":{
      "packageId":"bb2271a413fd44b882b5f8b1ed36926a",
      "type":"Axure:Master",
      "name":"ObjMas",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"7efc2c4d13c44b808e7556792aff433d",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontSize":"48px",
              "location":{
                "x":266,
                "y":560},
              "size":{
                "width":256,
                "height":55}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"f4855cde0167449ab67ee0042b702d3a",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"48px",
                  "location":{
                    "x":266,
                    "y":560},
                  "size":{
                    "width":256,
                    "height":55}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"c07bce8163b84af1b3d426be36aa5366",
            "label":"",
            "type":"horizontalLine",
            "styleType":"horizontalLine",
            "visible":true,
            "style":{
              "location":{
                "x":522,
                "y":582},
              "size":{
                "width":78,
                "height":10}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/monitor_kpis/u113_line.png"}}]}}},
  "objectPaths":{
    "3b3341b0ce12477bb5fbe572bc091b73":{
      "scriptId":"u0",
      "b7fd228ad5a240279ab302aee1b87b52":{
        "scriptId":"u1"},
      "2bfa5c8614094fb287d60d7d12e45ee2":{
        "scriptId":"u2"},
      "fc15c73249d34b269969db2b09f4acef":{
        "scriptId":"u3"},
      "4bb6471cc35846dab73c365841f3ef41":{
        "scriptId":"u4"}},
    "2b44143ea65c42f2af56f14803beadd0":{
      "scriptId":"u5"},
    "86a99fef77ad4af184da041f5fecd840":{
      "scriptId":"u6"},
    "9910920ce07d4698920868399b5a1762":{
      "scriptId":"u7"},
    "5d04512715704306a6df62cc6ba0d3ba":{
      "scriptId":"u8"},
    "df456e10d80a47888b17e5ad4825b458":{
      "scriptId":"u9"},
    "f6ecf526d0dd41d1851c40bdc2954c41":{
      "scriptId":"u10"},
    "8e98ab5591bd4232bfe9d79b2d98d201":{
      "scriptId":"u11"},
    "91b1a83ac46b4fcabb5c65b2fabd0601":{
      "scriptId":"u12"},
    "0871f300eee4411db15503df3bdd9a7f":{
      "scriptId":"u13"},
    "dd8db6965f84441f9cadba19a629ad43":{
      "scriptId":"u14"},
    "a0c382b5d98347748e24d6dc3b9498b6":{
      "scriptId":"u15"},
    "d9cc2189d01f44b88ac4444373ad1bd9":{
      "scriptId":"u16"},
    "c25a1d084af74eff9f904de644ea00cc":{
      "scriptId":"u17"},
    "f4ba4af9bf7844dcb49a2fc25251ed90":{
      "scriptId":"u18"},
    "b8e595d3603447b0ada2a0ba292e3c92":{
      "scriptId":"u19"},
    "0806f54a49c44af1abc3c4129dcd0f1e":{
      "scriptId":"u20"},
    "f3c162ecb6584006b7d18006e83042d7":{
      "scriptId":"u21"},
    "327b6e61a8364a6aa1d5989e290ff208":{
      "scriptId":"u22"},
    "2f51c3927d7243e78947d12aef9ac12a":{
      "scriptId":"u23"},
    "68e67fad1c91427eb64ce4841c19ab46":{
      "scriptId":"u24"},
    "d4de9fbd5cc743b982797ede8221a007":{
      "scriptId":"u25"},
    "f672408c4ad44c02b553c188cf88a5b7":{
      "scriptId":"u26"},
    "34643e800fd04a0cbedfc32dfe31ab59":{
      "scriptId":"u27"},
    "f8a4367eed254fdfa81a1af7990b01d5":{
      "scriptId":"u28"},
    "4dde4683ff9d4973a7b5b2d0011c4282":{
      "scriptId":"u29"},
    "7c9aea263ca8485285424faf5b67fcfc":{
      "scriptId":"u30"},
    "45dbbd1fddbc44c1a0d4b1d0087e6ce3":{
      "scriptId":"u31"},
    "7146b9d709e44dc88297ce42b8bb9575":{
      "scriptId":"u32"},
    "85a6806ba80e48e7966881ea5f229333":{
      "scriptId":"u33"},
    "5f395e468b1948bba45b3bfd85dd8d6e":{
      "scriptId":"u34"},
    "4672a4df58ad415c951ab6eb9e6d45fb":{
      "scriptId":"u35"},
    "4fbe66a8dd59480ca50873e9a3eabf90":{
      "scriptId":"u36"},
    "9645b5cff75e4bad81e4ed8dbca48498":{
      "scriptId":"u37"},
    "e44f27d8aec8462899f411b8fc84a74c":{
      "scriptId":"u38"},
    "a3bb3938704f4953a1ed0d7c2df328ef":{
      "scriptId":"u39"},
    "e3b34b0033834f368776bf771ce3b866":{
      "scriptId":"u40"},
    "3844c01aae414cfc9b7d73ac79748c66":{
      "scriptId":"u41"},
    "1bb4674967584d2aadc94148383e3740":{
      "scriptId":"u42"},
    "8579c9dff0174feb9706b9fac426274c":{
      "scriptId":"u43"},
    "360958bab1784c988bdc98db4a861c69":{
      "scriptId":"u44"},
    "fe01ab9294a4463c93613ea642117ea0":{
      "scriptId":"u45"},
    "a839af92aadd4a9ca40e54b498a354da":{
      "scriptId":"u46"},
    "99a901b597f74e92bfd33790bc5fe710":{
      "scriptId":"u47"},
    "134b66578ece4f13b5b1af42ecadffec":{
      "scriptId":"u48"},
    "e7cc29adaf0f496e89df8c8a37a6824c":{
      "scriptId":"u49"},
    "f310e6989dc74237a4835f90c01f5b25":{
      "scriptId":"u50"},
    "f03cb35631a94360928d669a114b90e4":{
      "scriptId":"u51"},
    "62f72b52862f4c53a99595f972379fd6":{
      "scriptId":"u52"},
    "7a1687d5806147fa8012905a5a3e70a6":{
      "scriptId":"u53"},
    "cd474d3c4a94443c8652180bdecff6c1":{
      "scriptId":"u54"},
    "a0d5e8def4404d4a9ea6f6c151dcbd68":{
      "scriptId":"u55"},
    "040fad864f6c491bb8a4773ac96dc0c4":{
      "scriptId":"u56"},
    "db18391362e14af9b5a00e63e38ebca1":{
      "scriptId":"u57"},
    "2c462d20c08c421db158590ad8e374d3":{
      "scriptId":"u58"},
    "1203f23aa22a45569c4b24c68af98ea7":{
      "scriptId":"u59"},
    "1ed3f596d4e646d79d7b9d84ff058c27":{
      "scriptId":"u60"},
    "896903fbb80148f0ad0f05aa115bd000":{
      "scriptId":"u61"},
    "c2e99c28b734447ca72097669e184b4b":{
      "scriptId":"u62"},
    "9fb50431a7fe41de9f13b75fa3782ca4":{
      "scriptId":"u63"},
    "6c114b1b5ef44c24b9796296abe676b0":{
      "scriptId":"u64"},
    "52396f85b4844e1eadf49f7ae5040b96":{
      "scriptId":"u65"},
    "077d8a6fd1724fb9b36fcb31d1c83b0f":{
      "scriptId":"u66"},
    "eb49d1b59ff841a999512edea8473c64":{
      "scriptId":"u67"},
    "8b771a795a2e42dbabe5bfa68b8a560b":{
      "scriptId":"u68"},
    "e12697d5027745ba84f3a0806632cebb":{
      "scriptId":"u69"},
    "5ab3a0151f2f438292d66cac8915bea2":{
      "scriptId":"u70"},
    "dc2310bb9a584c46b8b4cde4a131ce11":{
      "scriptId":"u71"},
    "93e662b319fc470db9f448ef30d81ddd":{
      "scriptId":"u72"},
    "d6171ed212d2487ea5722e51aeb2e69b":{
      "scriptId":"u73"},
    "65d6ab469f5f48adb320a92e0c51627d":{
      "scriptId":"u74"},
    "17c572e2f7ca453d933c96735c0138f4":{
      "scriptId":"u75"},
    "78bd03a41b7241358ce4697a20fe17ac":{
      "scriptId":"u76"},
    "da846085048b4324bf5374dc32a201f2":{
      "scriptId":"u77"},
    "d056ec2a622c46cb9cbf4526f3769aad":{
      "scriptId":"u78"},
    "b354c62f7e114dda9d2fab599dcd9ca9":{
      "scriptId":"u79"},
    "0f6783be79d144eea73608d0ce8880a9":{
      "scriptId":"u80"},
    "afe1e308b3ed439484978abc85daf64d":{
      "scriptId":"u81"},
    "aa672bbb39c44aebb5f42d9af80c390e":{
      "scriptId":"u82"},
    "7b1def5bd84c4653992266e73834acce":{
      "scriptId":"u83"},
    "c2e5c3850902473486a6529a995a37a7":{
      "scriptId":"u84"},
    "1f8373d2d2134fafa0a4380ffe760ac2":{
      "scriptId":"u85"},
    "1f107506025848bc902e81c4ef166a53":{
      "scriptId":"u86"},
    "3f54013c4b6841ef88e6a21d96c02de9":{
      "scriptId":"u87"},
    "a784848cf27a46cab91de50d9d5cf80a":{
      "scriptId":"u88"},
    "3ea70d23b03248a3a5150734fa9db815":{
      "scriptId":"u89",
      "7efc2c4d13c44b808e7556792aff433d":{
        "scriptId":"u90"},
      "f4855cde0167449ab67ee0042b702d3a":{
        "scriptId":"u91"},
      "c07bce8163b84af1b3d426be36aa5366":{
        "scriptId":"u92"}}}});