$axure.loadCurrentPage({
  "url":"dashboard.html",
  "generationDate":new Date(1520018785867.12),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"a7692b3a28e542f2b5e8052d6958c964",
    "type":"Axure:Page",
    "name":"Dashboard",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"0021e93d65fe4435a91bb9c7d732242d",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"4bf034ee21ba4a9c88f41f4b11a279dd"},
{
          "id":"e6ebc96c7db14abe889b5f2a9b9f2dcc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE5E5E5},
            "location":{
              "x":150,
              "y":117},
            "size":{
              "width":760,
              "height":1530}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"77b905d17a674dd2a05bf95fa916dcdc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE5E5E5},
                "location":{
                  "x":150,
                  "y":117},
                "size":{
                  "width":760,
                  "height":1530}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/dashboard/u5.png"}},
{
          "id":"9841430b455947c18a0a6cd456f4bab7",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"48px",
            "location":{
              "x":1259,
              "y":155},
            "size":{
              "width":491,
              "height":55}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"765e45fa5aae4717b41d08f13c226946",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"48px",
                "location":{
                  "x":1259,
                  "y":155},
                "size":{
                  "width":491,
                  "height":55}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4d7ed5a8508a488490491d55f9bde98e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"48px",
            "fill":{
              "fillType":"solid",
              "color":0xFF0099CC},
            "location":{
              "x":244,
              "y":643},
            "size":{
              "width":484,
              "height":110},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"12f0c25d6ab14007b072c76dd24c4364",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"48px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0099CC},
                "location":{
                  "x":244,
                  "y":643},
                "size":{
                  "width":484,
                  "height":110},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Create Plan in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"create_plan.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/dashboard/u9.png"}},
{
          "id":"eb0cc89192f040edb6d474f0ce82df55",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":150,
              "y":325},
            "size":{
              "width":198,
              "height":198}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"510575eb5b6c4d9ca15fab26353083b1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":150,
                  "y":325},
                "size":{
                  "width":198,
                  "height":198}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/dashboard/u11.png"}},
{
          "id":"3b48cc00c75746aeb390a8e843f3a627",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE5E5E5},
            "location":{
              "x":150,
              "y":493},
            "size":{
              "width":200,
              "height":100},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1f681276c4e94f5383d788a3dc765e4d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE5E5E5},
                "location":{
                  "x":150,
                  "y":493},
                "size":{
                  "width":200,
                  "height":100},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/dashboard/u13.png"}},
{
          "id":"afecf493700b4a0f994354ad9984dc33",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":408,
              "y":383},
            "size":{
              "width":300,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"02775736757c4d63a6cd60206f5c7f33",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":408,
                  "y":383},
                "size":{
                  "width":300,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"47f811098f3e4a4e875eb8d43a98ef14",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"48px",
            "fill":{
              "fillType":"solid",
              "color":0xFF00CC33},
            "location":{
              "x":244,
              "y":798},
            "size":{
              "width":484,
              "height":110},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"026c971e86384d788fee5e6d8a6a2933",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"48px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF00CC33},
                "location":{
                  "x":244,
                  "y":798},
                "size":{
                  "width":484,
                  "height":110},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/dashboard/u17.png"}},
{
          "id":"837bef1f13564544bb937323fc616b4c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":981,
              "y":304},
            "size":{
              "width":430,
              "height":290}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bae52f1e9c6542088684eaa9603ff820",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":981,
                  "y":304},
                "size":{
                  "width":430,
                  "height":290}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/dashboard/u19.png"}},
{
          "id":"bcd257dfe3fa4ebda31b3f95db2fee95",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1610,
              "y":304},
            "size":{
              "width":430,
              "height":290}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a058002b975143b7a16797c73cec4f77",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1610,
                  "y":304},
                "size":{
                  "width":430,
                  "height":290}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/dashboard/u19.png"}},
{
          "id":"8d30d68c7167452b834ac3d5163dccba",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":981,
              "y":709},
            "size":{
              "width":430,
              "height":290}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1d25c6b1907e456bb05d11c079962442",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":981,
                  "y":709},
                "size":{
                  "width":430,
                  "height":290}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/dashboard/u19.png"}},
{
          "id":"2b762439c492420ebecd493dbc2c0f18",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1610,
              "y":709},
            "size":{
              "width":430,
              "height":290}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1884a0960ca940779c14a911f51bd3bc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1610,
                  "y":709},
                "size":{
                  "width":430,
                  "height":290}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/dashboard/u19.png"}},
{
          "id":"ca692ead73784c8bbbe7d7ad3ffe468f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":981,
              "y":1112},
            "size":{
              "width":430,
              "height":290}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4489cfd6ee6b4b8db31ef0cd90d0848e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":981,
                  "y":1112},
                "size":{
                  "width":430,
                  "height":290}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/dashboard/u19.png"}},
{
          "id":"4d29e14ac54c4a1a9159795348c412ee",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1610,
              "y":1112},
            "size":{
              "width":430,
              "height":290}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"082f4be6e9e645db893093f16eaa847f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1610,
                  "y":1112},
                "size":{
                  "width":430,
                  "height":290}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/dashboard/u19.png"}},
{
          "id":"698ad736d09c4b738795f464c5cf8639",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":1120,
              "y":404},
            "size":{
              "width":180,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7cb46fd745ba4a449ef6578c016e0703",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1120,
                  "y":404},
                "size":{
                  "width":180,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7edb8f9c6e714f9ba6821e0f14d7c15a",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":1745,
              "y":404},
            "size":{
              "width":180,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f5d769e83b1946649faf65137459fd5d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1745,
                  "y":404},
                "size":{
                  "width":180,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"99912949bb2d4deeb72692da6d724766",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":1120,
              "y":826},
            "size":{
              "width":180,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"452e15eaf54f48f68c3dd88cc1dd8ce9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1120,
                  "y":826},
                "size":{
                  "width":180,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"837ff80aa9a24dc7a87b953ac6983f87",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":1745,
              "y":826},
            "size":{
              "width":180,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1bc762d4df9543a7a6ac7d27fd528dd4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1745,
                  "y":826},
                "size":{
                  "width":180,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7293d000a3594cd087e7b884b0c8661f",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":1120,
              "y":1224},
            "size":{
              "width":180,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1e45ae1ea64b478c9b5a19976bc8d792",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1120,
                  "y":1224},
                "size":{
                  "width":180,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d7913c932e614b6bab1059cfa42a43d7",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":1745,
              "y":1224},
            "size":{
              "width":180,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"33384187c0e14186913b81ffb36b3582",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1745,
                  "y":1224},
                "size":{
                  "width":180,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"78b126e8f980459ea157eb652d9e5705",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":168,
              "y":1613},
            "size":{
              "width":141,
              "height":37},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4c1574f90e214ff19c5a13d96f025da4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":168,
                  "y":1613},
                "size":{
                  "width":141,
                  "height":37},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"077787242a3c49059cf9fcf625560bb3",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":698,
              "y":1613},
            "size":{
              "width":107,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"73d2c86a01bf42d79a07b163aa135db4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":698,
                  "y":1613},
                "size":{
                  "width":107,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Low Fi Index in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"low_fi_index.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"22453e6e35e04f7d824ddb7e8e909620",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":1205,
              "y":550},
            "size":{
              "width":171,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a19e092bc0854351b1519631d73ba524",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1205,
                  "y":550},
                "size":{
                  "width":171,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b69b59053096405db8a17c5431c4d416",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":1205,
              "y":952},
            "size":{
              "width":171,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bfa5db5b5fb440019b86a566c32d3197",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1205,
                  "y":952},
                "size":{
                  "width":171,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d2b0f39904144a2f88cbdae33b039767",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":1835,
              "y":952},
            "size":{
              "width":171,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"687a1071dbb94230a2769764b09a6a99",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1835,
                  "y":952},
                "size":{
                  "width":171,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c4eb7b784c464019bdabad0a07b460c4",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":1835,
              "y":546},
            "size":{
              "width":171,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aca85b94680f4bdb94fd1554e3c3ae3a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1835,
                  "y":546},
                "size":{
                  "width":171,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ff65806c928e49c3bb3c5c2722a2f301",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":1835,
              "y":1347},
            "size":{
              "width":171,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5478076eceba4e44be6a03448cc1647d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1835,
                  "y":1347},
                "size":{
                  "width":171,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8f970bdc50714877bbda21d488db9676",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":1205,
              "y":1350},
            "size":{
              "width":171,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2e4eea90a9ba43c2bbb4ddd682c19f01",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1205,
                  "y":1350},
                "size":{
                  "width":171,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
    "4bf034ee21ba4a9c88f41f4b11a279dd":{
      "packageId":"4bf034ee21ba4a9c88f41f4b11a279dd",
      "type":"Axure:Master",
      "name":"ipad",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"b7fd228ad5a240279ab302aee1b87b52",
            "label":"",
            "type":"flowShape",
            "styleType":"flowShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF333333},
              "size":{
                "width":2352,
                "height":1764},
              "borderFill":{
                "fillType":"linearGradient",
                "colors":[{
                    "color":0xFF000099},
{
                    "color":0xFF000099},
{
                    "color":0xFF000000},
{
                    "color":0xFF000000}]}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"2bfa5c8614094fb287d60d7d12e45ee2",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF333333},
                  "size":{
                    "width":2352,
                    "height":1764},
                  "borderFill":{
                    "fillType":"linearGradient",
                    "colors":[{
                        "color":0xFF000099},
{
                        "color":0xFF000099},
{
                        "color":0xFF000000},
{
                        "color":0xFF000000}]}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/low_fi_index/u1.png"}},
{
            "id":"fc15c73249d34b269969db2b09f4acef",
            "label":"",
            "type":"flowShape",
            "styleType":"flowShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"linearGradient",
                "colors":[{
                    "color":0xFFFFFFFF},
{
                    "color":0xFFFFFFFF},
{
                    "color":0xFFE4E4E4},
{
                    "color":0xFFE4E4E4}]},
              "location":{
                "x":152,
                "y":114},
              "size":{
                "width":2048,
                "height":1536}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"4bb6471cc35846dab73c365841f3ef41",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"linearGradient",
                    "colors":[{
                        "color":0xFFFFFFFF},
{
                        "color":0xFFFFFFFF},
{
                        "color":0xFFE4E4E4},
{
                        "color":0xFFE4E4E4}]},
                  "location":{
                    "x":152,
                    "y":114},
                  "size":{
                    "width":2048,
                    "height":1536}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/low_fi_index/u3.png"}}]}}},
  "objectPaths":{
    "0021e93d65fe4435a91bb9c7d732242d":{
      "scriptId":"u0",
      "b7fd228ad5a240279ab302aee1b87b52":{
        "scriptId":"u1"},
      "2bfa5c8614094fb287d60d7d12e45ee2":{
        "scriptId":"u2"},
      "fc15c73249d34b269969db2b09f4acef":{
        "scriptId":"u3"},
      "4bb6471cc35846dab73c365841f3ef41":{
        "scriptId":"u4"}},
    "e6ebc96c7db14abe889b5f2a9b9f2dcc":{
      "scriptId":"u5"},
    "77b905d17a674dd2a05bf95fa916dcdc":{
      "scriptId":"u6"},
    "9841430b455947c18a0a6cd456f4bab7":{
      "scriptId":"u7"},
    "765e45fa5aae4717b41d08f13c226946":{
      "scriptId":"u8"},
    "4d7ed5a8508a488490491d55f9bde98e":{
      "scriptId":"u9"},
    "12f0c25d6ab14007b072c76dd24c4364":{
      "scriptId":"u10"},
    "eb0cc89192f040edb6d474f0ce82df55":{
      "scriptId":"u11"},
    "510575eb5b6c4d9ca15fab26353083b1":{
      "scriptId":"u12"},
    "3b48cc00c75746aeb390a8e843f3a627":{
      "scriptId":"u13"},
    "1f681276c4e94f5383d788a3dc765e4d":{
      "scriptId":"u14"},
    "afecf493700b4a0f994354ad9984dc33":{
      "scriptId":"u15"},
    "02775736757c4d63a6cd60206f5c7f33":{
      "scriptId":"u16"},
    "47f811098f3e4a4e875eb8d43a98ef14":{
      "scriptId":"u17"},
    "026c971e86384d788fee5e6d8a6a2933":{
      "scriptId":"u18"},
    "837bef1f13564544bb937323fc616b4c":{
      "scriptId":"u19"},
    "bae52f1e9c6542088684eaa9603ff820":{
      "scriptId":"u20"},
    "bcd257dfe3fa4ebda31b3f95db2fee95":{
      "scriptId":"u21"},
    "a058002b975143b7a16797c73cec4f77":{
      "scriptId":"u22"},
    "8d30d68c7167452b834ac3d5163dccba":{
      "scriptId":"u23"},
    "1d25c6b1907e456bb05d11c079962442":{
      "scriptId":"u24"},
    "2b762439c492420ebecd493dbc2c0f18":{
      "scriptId":"u25"},
    "1884a0960ca940779c14a911f51bd3bc":{
      "scriptId":"u26"},
    "ca692ead73784c8bbbe7d7ad3ffe468f":{
      "scriptId":"u27"},
    "4489cfd6ee6b4b8db31ef0cd90d0848e":{
      "scriptId":"u28"},
    "4d29e14ac54c4a1a9159795348c412ee":{
      "scriptId":"u29"},
    "082f4be6e9e645db893093f16eaa847f":{
      "scriptId":"u30"},
    "698ad736d09c4b738795f464c5cf8639":{
      "scriptId":"u31"},
    "7cb46fd745ba4a449ef6578c016e0703":{
      "scriptId":"u32"},
    "7edb8f9c6e714f9ba6821e0f14d7c15a":{
      "scriptId":"u33"},
    "f5d769e83b1946649faf65137459fd5d":{
      "scriptId":"u34"},
    "99912949bb2d4deeb72692da6d724766":{
      "scriptId":"u35"},
    "452e15eaf54f48f68c3dd88cc1dd8ce9":{
      "scriptId":"u36"},
    "837ff80aa9a24dc7a87b953ac6983f87":{
      "scriptId":"u37"},
    "1bc762d4df9543a7a6ac7d27fd528dd4":{
      "scriptId":"u38"},
    "7293d000a3594cd087e7b884b0c8661f":{
      "scriptId":"u39"},
    "1e45ae1ea64b478c9b5a19976bc8d792":{
      "scriptId":"u40"},
    "d7913c932e614b6bab1059cfa42a43d7":{
      "scriptId":"u41"},
    "33384187c0e14186913b81ffb36b3582":{
      "scriptId":"u42"},
    "78b126e8f980459ea157eb652d9e5705":{
      "scriptId":"u43"},
    "4c1574f90e214ff19c5a13d96f025da4":{
      "scriptId":"u44"},
    "077787242a3c49059cf9fcf625560bb3":{
      "scriptId":"u45"},
    "73d2c86a01bf42d79a07b163aa135db4":{
      "scriptId":"u46"},
    "22453e6e35e04f7d824ddb7e8e909620":{
      "scriptId":"u47"},
    "a19e092bc0854351b1519631d73ba524":{
      "scriptId":"u48"},
    "b69b59053096405db8a17c5431c4d416":{
      "scriptId":"u49"},
    "bfa5db5b5fb440019b86a566c32d3197":{
      "scriptId":"u50"},
    "d2b0f39904144a2f88cbdae33b039767":{
      "scriptId":"u51"},
    "687a1071dbb94230a2769764b09a6a99":{
      "scriptId":"u52"},
    "c4eb7b784c464019bdabad0a07b460c4":{
      "scriptId":"u53"},
    "aca85b94680f4bdb94fd1554e3c3ae3a":{
      "scriptId":"u54"},
    "ff65806c928e49c3bb3c5c2722a2f301":{
      "scriptId":"u55"},
    "5478076eceba4e44be6a03448cc1647d":{
      "scriptId":"u56"},
    "8f970bdc50714877bbda21d488db9676":{
      "scriptId":"u57"},
    "2e4eea90a9ba43c2bbb4ddd682c19f01":{
      "scriptId":"u58"}}});