$axure.loadCurrentPage({
  "url":"stakeolders.html",
  "generationDate":new Date(1520018788887.78),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"0e7fd91ddb0746ef842a70e9dd314e5f",
    "type":"Axure:Page",
    "name":"Stakeolders",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"02e9cd5ca75844e3a970fdabc420df44",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"4bf034ee21ba4a9c88f41f4b11a279dd"},
{
          "id":"32660632078546f4bcb46027faebc0f8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF3399CC},
            "location":{
              "x":151,
              "y":117},
            "size":{
              "width":2050,
              "height":1530}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"04e9038d779947f0bc0754417a9c7134",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF3399CC},
                "location":{
                  "x":151,
                  "y":117},
                "size":{
                  "width":2050,
                  "height":1530}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/create_plan/u5.png"}},
{
          "id":"999c8c7aead64a0ab73c0d981246e9fb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":210,
              "y":499},
            "size":{
              "width":1930,
              "height":1091}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ed8fe9f03e0747e4ad2b0a9b103cd449",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":210,
                  "y":499},
                "size":{
                  "width":1930,
                  "height":1091}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/create_plan/u7.png"}},
{
          "id":"e4a87837dc5e4ee2a92a3df2b7d858b9",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"48px",
            "location":{
              "x":276,
              "y":560},
            "size":{
              "width":407,
              "height":55}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"701710884a5944d196379a2028e0514f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"48px",
                "location":{
                  "x":276,
                  "y":560},
                "size":{
                  "width":407,
                  "height":55}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f178f903d92c48a8b497fb62c9831b3b",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"72px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":778,
              "y":188},
            "size":{
              "width":797,
              "height":82},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a0ba39e671704dbd93ef079fc642f73b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"72px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":778,
                  "y":188},
                "size":{
                  "width":797,
                  "height":82},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"69380b9999cf42f7960eabc6d81f702a",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFF00FF99},
{
                  "color":0xFF00FF99},
{
                  "color":0xFFE4E4E4},
{
                  "color":0xFFE4E4E4}]},
            "location":{
              "x":230,
              "y":349},
            "size":{
              "width":110,
              "height":110}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"878119c3fc444e52af42fedf8e44baa9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFF00FF99},
{
                      "color":0xFF00FF99},
{
                      "color":0xFFE4E4E4},
{
                      "color":0xFFE4E4E4}]},
                "location":{
                  "x":230,
                  "y":349},
                "size":{
                  "width":110,
                  "height":110}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Create Plan in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"create_plan.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/monitor_kpis/u13.png"}},
{
          "id":"0077e0217e714d9e9a3fd01a33449980",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":276,
              "y":386},
            "size":{
              "width":19,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"22e742132409495b86f5dd6624e42dff",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":276,
                  "y":386},
                "size":{
                  "width":19,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"89cad0842cde45d2acfa786dfb619bd3",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFF3BF8AC},
{
                  "color":0xFF3BF8AC},
{
                  "color":0xFFE4E4E4},
{
                  "color":0xFFE4E4E4}]},
            "location":{
              "x":615,
              "y":349},
            "size":{
              "width":110,
              "height":110}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"65a4658e77aa4522812168dd9764e05b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFF3BF8AC},
{
                      "color":0xFF3BF8AC},
{
                      "color":0xFFE4E4E4},
{
                      "color":0xFFE4E4E4}]},
                "location":{
                  "x":615,
                  "y":349},
                "size":{
                  "width":110,
                  "height":110}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Monitor KPIs in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"monitor_kpis.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/create_plan/u15.png"}},
{
          "id":"25fd8dd463664e8d8aa96659774b44d3",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":661,
              "y":386},
            "size":{
              "width":19,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bc77fd6de7734536a57ff94742e9dd7c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":661,
                  "y":386},
                "size":{
                  "width":19,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7bfd9091311e43fdaa00e928d5dc900e",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFF3BF8AC},
{
                  "color":0xFF3BF8AC},
{
                  "color":0xFFE4E4E4},
{
                  "color":0xFFE4E4E4}]},
            "location":{
              "x":1027,
              "y":349},
            "size":{
              "width":110,
              "height":110}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4025257173b14982903a54ac3b735e3e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFF3BF8AC},
{
                      "color":0xFF3BF8AC},
{
                      "color":0xFFE4E4E4},
{
                      "color":0xFFE4E4E4}]},
                "location":{
                  "x":1027,
                  "y":349},
                "size":{
                  "width":110,
                  "height":110}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Risks in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"risks.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/create_plan/u15.png"}},
{
          "id":"23aac5a61b014ed1b6d4e96bdc8a91a4",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":1073,
              "y":386},
            "size":{
              "width":19,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"124f7057947545ce944e757c87c406c5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1073,
                  "y":386},
                "size":{
                  "width":19,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"45794870e9d24a34a113050f1fb664bb",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFF3BF8AC},
{
                  "color":0xFF3BF8AC},
{
                  "color":0xFFE4E4E4},
{
                  "color":0xFFE4E4E4}]},
            "location":{
              "x":1416,
              "y":349},
            "size":{
              "width":110,
              "height":110}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6d7ca24d91b9450d87c747129859af41",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFF3BF8AC},
{
                      "color":0xFF3BF8AC},
{
                      "color":0xFFE4E4E4},
{
                      "color":0xFFE4E4E4}]},
                "location":{
                  "x":1416,
                  "y":349},
                "size":{
                  "width":110,
                  "height":110}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Capabilities in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"capabilities.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/create_plan/u15.png"}},
{
          "id":"01ca6ea85d20413fb6d137e2cc22035e",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":1462,
              "y":386},
            "size":{
              "width":19,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"48165c6425484df998bab9304a76fb18",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1462,
                  "y":386},
                "size":{
                  "width":19,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d0c4884b2d204205a78fdd6908fc3da0",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFF3BF8AC},
{
                  "color":0xFF3BF8AC},
{
                  "color":0xFFE4E4E4},
{
                  "color":0xFFE4E4E4}]},
            "location":{
              "x":1759,
              "y":349},
            "size":{
              "width":110,
              "height":110}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"19baf070aa0947d5a99f8d6682c6ce44",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFF3BF8AC},
{
                      "color":0xFF3BF8AC},
{
                      "color":0xFFE4E4E4},
{
                      "color":0xFFE4E4E4}]},
                "location":{
                  "x":1759,
                  "y":349},
                "size":{
                  "width":110,
                  "height":110}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/create_plan/u15.png"}},
{
          "id":"1b9fc09dcf5d49ca913a9c8015587ab5",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":1805,
              "y":386},
            "size":{
              "width":19,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"740e157a8a96455eb0a2447f0ad8f523",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1805,
                  "y":386},
                "size":{
                  "width":19,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"047adf1d71e14ca9a8e5606c0a49c348",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":2027,
              "y":349},
            "size":{
              "width":110,
              "height":110}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bb14d68bbd954e1e9974d7fdc31b4c24",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":2027,
                  "y":349},
                "size":{
                  "width":110,
                  "height":110}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/create_plan/u19.png"}},
{
          "id":"5c420aa9364d4d0780bc0a9bb5d6b205",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":2073,
              "y":386},
            "size":{
              "width":19,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"183ee5ea56934493865c477b734a0330",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":2073,
                  "y":386},
                "size":{
                  "width":19,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ecb252d3bbb64865ace7383814cbd21b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"48px",
            "fill":{
              "fillType":"solid",
              "color":0xFF00CC99},
            "location":{
              "x":1892,
              "y":1410},
            "size":{
              "width":248,
              "height":180},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"76ea5b34e6bc4c37a537cc2c50b12252",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"48px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF00CC99},
                "location":{
                  "x":1892,
                  "y":1410},
                "size":{
                  "width":248,
                  "height":180},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Print in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"print.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/create_plan/u48.png"}},
{
          "id":"a9c23c78cc2c49468f1bccbacceef4ee",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":276,
              "y":794},
            "size":{
              "width":614,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8677a6106a5c4290af2dda2efa686114",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":276,
                  "y":794},
                "size":{
                  "width":614,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/monitor_kpis/u39.png"}},
{
          "id":"cae52a9e2fb84456a16c8f6e16ae0779",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"36px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":325,
              "y":824},
            "size":{
              "width":99,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6c946db8f5e24fe78fa7889abe4a9ec8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"36px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":325,
                  "y":824},
                "size":{
                  "width":99,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"be8f1353ae704a9997c7249a9e3ad9de",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"36px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":325,
              "y":936},
            "size":{
              "width":235,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2bfecce1636e46a3af4027aac8c12901",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"36px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":325,
                  "y":936},
                "size":{
                  "width":235,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5e1e489642864aaf9d007a0ca8d7ba46",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"48px",
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":318.5,
              "y":1030},
            "size":{
              "width":248,
              "height":78},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ee4796062d6243aabd7e9f5aa3a7be0e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"48px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":318.5,
                  "y":1030},
                "size":{
                  "width":248,
                  "height":78},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/create_plan/u63.png"}},
{
          "id":"5334779751c0487db0610ebb8ea8d814",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":1088,
              "y":645},
            "size":{
              "width":841,
              "height":258}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ad327ffb476c43548f2232c0a366510e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontSize":"36px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "size":{
                  "width":262,
                  "height":86}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"98ba323daecc4a9d8eb652a8f2986b9b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"36px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "size":{
                      "width":262,
                      "height":86}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/monitor_kpis/u58.png"}},
{
              "id":"e9ed9393bfad44f581359a0e94c6956c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontSize":"36px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":262,
                  "y":0},
                "size":{
                  "width":242,
                  "height":86}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"820f133e4cf64468b988be5c915a860b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"36px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":262,
                      "y":0},
                    "size":{
                      "width":242,
                      "height":86}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/monitor_kpis/u60.png"}},
{
              "id":"8ab8f95bd12f4856b44a62a6fefc99b5",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontSize":"36px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":504,
                  "y":0},
                "size":{
                  "width":252,
                  "height":86}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"3ff125032bc04040b0d420ac425e5c89",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"36px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":504,
                      "y":0},
                    "size":{
                      "width":252,
                      "height":86}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/stakeolders/u52.png"}},
{
              "id":"9974035e3cfd48709bf4602a5ee0659a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontSize":"36px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":86},
                "size":{
                  "width":262,
                  "height":86}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"9825606c29664aef98bf7eb792ceeb90",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"36px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":86},
                    "size":{
                      "width":262,
                      "height":86}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/monitor_kpis/u58.png"}},
{
              "id":"edbe53f424b54dc2b536ba27f8e7f6d0",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontSize":"36px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":262,
                  "y":86},
                "size":{
                  "width":242,
                  "height":86}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"1446822d5d264622a53d106636a0a2f7",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"36px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":262,
                      "y":86},
                    "size":{
                      "width":242,
                      "height":86}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/monitor_kpis/u60.png"}},
{
              "id":"6a884838ec1148e783d3e076933c3f57",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontSize":"36px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":504,
                  "y":86},
                "size":{
                  "width":252,
                  "height":86}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"370ec1a5984841bfa0fcc76920f6fbab",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"36px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":504,
                      "y":86},
                    "size":{
                      "width":252,
                      "height":86}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/stakeolders/u52.png"}},
{
              "id":"ed3f60aed87149908c8b8ae5c3f3d52c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontSize":"36px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":172},
                "size":{
                  "width":262,
                  "height":86}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"2e6c135914824c4d899e00d4ee1ca993",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"36px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":172},
                    "size":{
                      "width":262,
                      "height":86}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/stakeolders/u64.png"}},
{
              "id":"9222a69203f24dce98da087ef613aee7",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontSize":"36px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":262,
                  "y":172},
                "size":{
                  "width":242,
                  "height":86}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c2623ea7e1e1445990f85c833269dceb",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"36px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":262,
                      "y":172},
                    "size":{
                      "width":242,
                      "height":86}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/stakeolders/u66.png"}},
{
              "id":"8441155521314d29995963aae5bf5516",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontSize":"36px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":504,
                  "y":172},
                "size":{
                  "width":252,
                  "height":86}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"13dca0519299464984bcfc6ac7058bd1",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"36px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":504,
                      "y":172},
                    "size":{
                      "width":252,
                      "height":86}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/stakeolders/u68.png"}},
{
              "id":"b2d4dcc575a44c01a477121a379b596e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontSize":"36px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":756,
                  "y":0},
                "size":{
                  "width":85,
                  "height":86}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0a10ca44c9c54a44990f70f667140f67",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"36px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":756,
                      "y":0},
                    "size":{
                      "width":85,
                      "height":86}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/stakeolders/u54.png"}},
{
              "id":"35110ed04df14ac095b4c039be06b2af",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontSize":"36px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":756,
                  "y":86},
                "size":{
                  "width":85,
                  "height":86}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"15afa704e75940de878b1b8e5e662ced",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"36px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":756,
                      "y":86},
                    "size":{
                      "width":85,
                      "height":86}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/stakeolders/u54.png"}},
{
              "id":"98fb9bbf0c67412991d0b1511d308c59",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontSize":"36px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":756,
                  "y":172},
                "size":{
                  "width":85,
                  "height":86}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"7dbace6c5a3d4e0082664b6e80fb82d1",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"36px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":756,
                      "y":172},
                    "size":{
                      "width":85,
                      "height":86}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/stakeolders/u70.png"}}]},
{
          "id":"84a281662219451a86e3dd907fac9da3",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"36px",
            "location":{
              "x":1677,
              "y":661},
            "size":{
              "width":111,
              "height":41}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3f9c2abe2e6540f5b3597e7473728a0d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"36px",
                "location":{
                  "x":1677,
                  "y":661},
                "size":{
                  "width":111,
                  "height":41}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4f8b894f8eb24c9b96fe74d58e7ac5a5",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"36px",
            "location":{
              "x":1389,
              "y":661},
            "size":{
              "width":99,
              "height":41}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b4d96452f955411498fa4b7becf3e2ae",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"36px",
                "location":{
                  "x":1389,
                  "y":661},
                "size":{
                  "width":99,
                  "height":41}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f679219db48843bcaac91262296cb545",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":276,
              "y":661},
            "size":{
              "width":514,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bdadef9504f449da84d7ab71faaaea15",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":276,
                  "y":661},
                "size":{
                  "width":514,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/stakeolders/u76.png"}},
{
          "id":"843a3d864f43464faaa3a4e15b1ba76c",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"36px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":325,
              "y":691},
            "size":{
              "width":154,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0d645085ca8a4dc1bcc0ab01cee3630f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"36px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":325,
                  "y":691},
                "size":{
                  "width":154,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e7a3de690c774b62984d3767d96b535e",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"36px",
            "location":{
              "x":1123,
              "y":661},
            "size":{
              "width":134,
              "height":41}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c49674ab12cc4f74a9e42950fd49e35a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"36px",
                "location":{
                  "x":1123,
                  "y":661},
                "size":{
                  "width":134,
                  "height":41}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5378c4eb566c4a1eac953df04ac74ed2",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":800,
              "y":655},
            "size":{
              "width":118,
              "height":118}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"33d44a3ea455463f858304930d08abb1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":800,
                  "y":655},
                "size":{
                  "width":118,
                  "height":118}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/stakeolders/u82.png"}},
{
          "id":"e56a70dce504484684582714e0d94770",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFF,
              "opacity":0},
            "location":{
              "x":800,
              "y":756},
            "size":{
              "width":60,
              "height":22},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e13d5784f3744e42bb687db70d9bd7a2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF,
                  "opacity":0},
                "location":{
                  "x":800,
                  "y":756},
                "size":{
                  "width":60,
                  "height":22},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/stakeolders/u84.png"}},
{
          "id":"e1889c93c93f451999c1bb3225c1eea0",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":600,
              "y":936},
            "size":{
              "width":200,
              "height":44}},
          "adaptiveStyles":{
}},
{
          "id":"40f731c85fe54bd7918c675c80daaeb0",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1860,
              "y":750},
            "size":{
              "width":43,
              "height":43}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"22af8afc9cf14bc89a318cdbb4681a87",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1860,
                  "y":750},
                "size":{
                  "width":43,
                  "height":43}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/create_plan/u9.png"}},
{
          "id":"185e1c669bbd46e9a143da9803c59a81",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":1860,
              "y":785},
            "size":{
              "width":38,
              "height":13},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"73b51c8a47c6442992289d996fc52c55",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":1860,
                  "y":785},
                "size":{
                  "width":38,
                  "height":13},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/stakeolders/u89.png"}},
{
          "id":"8e573a500d9349638fe213706ccb5b94",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1860,
              "y":843},
            "size":{
              "width":43,
              "height":43}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d4bb5c969d1e4fc8bd4f3d7fd35efad3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1860,
                  "y":843},
                "size":{
                  "width":43,
                  "height":43}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/create_plan/u9.png"}},
{
          "id":"27779bac5d93494cb7e59dafed506074",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":1860,
              "y":878},
            "size":{
              "width":38,
              "height":13},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b1ca6b1a709747acb2ffb9c8a80dbf9f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":1860,
                  "y":878},
                "size":{
                  "width":38,
                  "height":13},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/stakeolders/u89.png"}},
{
          "id":"349ea80fab8545889a14ab70314406f4",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":1073,
              "y":1010},
            "size":{
              "width":633,
              "height":140}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4e049243518f4cbd8c04811a2813b0be",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1073,
                  "y":1010},
                "size":{
                  "width":633,
                  "height":140}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/stakeolders/u95.png"}},
{
          "id":"45bbe37a2e864a1abe4a3354874b0b74",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"36px",
            "location":{
              "x":1106,
              "y":1041},
            "size":{
              "width":590,
              "height":119}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d44292d94df44ac1b6759be5f8ba85fe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"36px",
                "location":{
                  "x":1106,
                  "y":1041},
                "size":{
                  "width":590,
                  "height":119}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
    "4bf034ee21ba4a9c88f41f4b11a279dd":{
      "packageId":"4bf034ee21ba4a9c88f41f4b11a279dd",
      "type":"Axure:Master",
      "name":"ipad",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"b7fd228ad5a240279ab302aee1b87b52",
            "label":"",
            "type":"flowShape",
            "styleType":"flowShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF333333},
              "size":{
                "width":2352,
                "height":1764},
              "borderFill":{
                "fillType":"linearGradient",
                "colors":[{
                    "color":0xFF000099},
{
                    "color":0xFF000099},
{
                    "color":0xFF000000},
{
                    "color":0xFF000000}]}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"2bfa5c8614094fb287d60d7d12e45ee2",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF333333},
                  "size":{
                    "width":2352,
                    "height":1764},
                  "borderFill":{
                    "fillType":"linearGradient",
                    "colors":[{
                        "color":0xFF000099},
{
                        "color":0xFF000099},
{
                        "color":0xFF000000},
{
                        "color":0xFF000000}]}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/low_fi_index/u1.png"}},
{
            "id":"fc15c73249d34b269969db2b09f4acef",
            "label":"",
            "type":"flowShape",
            "styleType":"flowShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"linearGradient",
                "colors":[{
                    "color":0xFFFFFFFF},
{
                    "color":0xFFFFFFFF},
{
                    "color":0xFFE4E4E4},
{
                    "color":0xFFE4E4E4}]},
              "location":{
                "x":152,
                "y":114},
              "size":{
                "width":2048,
                "height":1536}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"4bb6471cc35846dab73c365841f3ef41",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"linearGradient",
                    "colors":[{
                        "color":0xFFFFFFFF},
{
                        "color":0xFFFFFFFF},
{
                        "color":0xFFE4E4E4},
{
                        "color":0xFFE4E4E4}]},
                  "location":{
                    "x":152,
                    "y":114},
                  "size":{
                    "width":2048,
                    "height":1536}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/low_fi_index/u3.png"}}]}}},
  "objectPaths":{
    "02e9cd5ca75844e3a970fdabc420df44":{
      "scriptId":"u0",
      "b7fd228ad5a240279ab302aee1b87b52":{
        "scriptId":"u1"},
      "2bfa5c8614094fb287d60d7d12e45ee2":{
        "scriptId":"u2"},
      "fc15c73249d34b269969db2b09f4acef":{
        "scriptId":"u3"},
      "4bb6471cc35846dab73c365841f3ef41":{
        "scriptId":"u4"}},
    "32660632078546f4bcb46027faebc0f8":{
      "scriptId":"u5"},
    "04e9038d779947f0bc0754417a9c7134":{
      "scriptId":"u6"},
    "999c8c7aead64a0ab73c0d981246e9fb":{
      "scriptId":"u7"},
    "ed8fe9f03e0747e4ad2b0a9b103cd449":{
      "scriptId":"u8"},
    "e4a87837dc5e4ee2a92a3df2b7d858b9":{
      "scriptId":"u9"},
    "701710884a5944d196379a2028e0514f":{
      "scriptId":"u10"},
    "f178f903d92c48a8b497fb62c9831b3b":{
      "scriptId":"u11"},
    "a0ba39e671704dbd93ef079fc642f73b":{
      "scriptId":"u12"},
    "69380b9999cf42f7960eabc6d81f702a":{
      "scriptId":"u13"},
    "878119c3fc444e52af42fedf8e44baa9":{
      "scriptId":"u14"},
    "0077e0217e714d9e9a3fd01a33449980":{
      "scriptId":"u15"},
    "22e742132409495b86f5dd6624e42dff":{
      "scriptId":"u16"},
    "89cad0842cde45d2acfa786dfb619bd3":{
      "scriptId":"u17"},
    "65a4658e77aa4522812168dd9764e05b":{
      "scriptId":"u18"},
    "25fd8dd463664e8d8aa96659774b44d3":{
      "scriptId":"u19"},
    "bc77fd6de7734536a57ff94742e9dd7c":{
      "scriptId":"u20"},
    "7bfd9091311e43fdaa00e928d5dc900e":{
      "scriptId":"u21"},
    "4025257173b14982903a54ac3b735e3e":{
      "scriptId":"u22"},
    "23aac5a61b014ed1b6d4e96bdc8a91a4":{
      "scriptId":"u23"},
    "124f7057947545ce944e757c87c406c5":{
      "scriptId":"u24"},
    "45794870e9d24a34a113050f1fb664bb":{
      "scriptId":"u25"},
    "6d7ca24d91b9450d87c747129859af41":{
      "scriptId":"u26"},
    "01ca6ea85d20413fb6d137e2cc22035e":{
      "scriptId":"u27"},
    "48165c6425484df998bab9304a76fb18":{
      "scriptId":"u28"},
    "d0c4884b2d204205a78fdd6908fc3da0":{
      "scriptId":"u29"},
    "19baf070aa0947d5a99f8d6682c6ce44":{
      "scriptId":"u30"},
    "1b9fc09dcf5d49ca913a9c8015587ab5":{
      "scriptId":"u31"},
    "740e157a8a96455eb0a2447f0ad8f523":{
      "scriptId":"u32"},
    "047adf1d71e14ca9a8e5606c0a49c348":{
      "scriptId":"u33"},
    "bb14d68bbd954e1e9974d7fdc31b4c24":{
      "scriptId":"u34"},
    "5c420aa9364d4d0780bc0a9bb5d6b205":{
      "scriptId":"u35"},
    "183ee5ea56934493865c477b734a0330":{
      "scriptId":"u36"},
    "ecb252d3bbb64865ace7383814cbd21b":{
      "scriptId":"u37"},
    "76ea5b34e6bc4c37a537cc2c50b12252":{
      "scriptId":"u38"},
    "a9c23c78cc2c49468f1bccbacceef4ee":{
      "scriptId":"u39"},
    "8677a6106a5c4290af2dda2efa686114":{
      "scriptId":"u40"},
    "cae52a9e2fb84456a16c8f6e16ae0779":{
      "scriptId":"u41"},
    "6c946db8f5e24fe78fa7889abe4a9ec8":{
      "scriptId":"u42"},
    "be8f1353ae704a9997c7249a9e3ad9de":{
      "scriptId":"u43"},
    "2bfecce1636e46a3af4027aac8c12901":{
      "scriptId":"u44"},
    "5e1e489642864aaf9d007a0ca8d7ba46":{
      "scriptId":"u45"},
    "ee4796062d6243aabd7e9f5aa3a7be0e":{
      "scriptId":"u46"},
    "5334779751c0487db0610ebb8ea8d814":{
      "scriptId":"u47"},
    "ad327ffb476c43548f2232c0a366510e":{
      "scriptId":"u48"},
    "98ba323daecc4a9d8eb652a8f2986b9b":{
      "scriptId":"u49"},
    "e9ed9393bfad44f581359a0e94c6956c":{
      "scriptId":"u50"},
    "820f133e4cf64468b988be5c915a860b":{
      "scriptId":"u51"},
    "8ab8f95bd12f4856b44a62a6fefc99b5":{
      "scriptId":"u52"},
    "3ff125032bc04040b0d420ac425e5c89":{
      "scriptId":"u53"},
    "b2d4dcc575a44c01a477121a379b596e":{
      "scriptId":"u54"},
    "0a10ca44c9c54a44990f70f667140f67":{
      "scriptId":"u55"},
    "9974035e3cfd48709bf4602a5ee0659a":{
      "scriptId":"u56"},
    "9825606c29664aef98bf7eb792ceeb90":{
      "scriptId":"u57"},
    "edbe53f424b54dc2b536ba27f8e7f6d0":{
      "scriptId":"u58"},
    "1446822d5d264622a53d106636a0a2f7":{
      "scriptId":"u59"},
    "6a884838ec1148e783d3e076933c3f57":{
      "scriptId":"u60"},
    "370ec1a5984841bfa0fcc76920f6fbab":{
      "scriptId":"u61"},
    "35110ed04df14ac095b4c039be06b2af":{
      "scriptId":"u62"},
    "15afa704e75940de878b1b8e5e662ced":{
      "scriptId":"u63"},
    "ed3f60aed87149908c8b8ae5c3f3d52c":{
      "scriptId":"u64"},
    "2e6c135914824c4d899e00d4ee1ca993":{
      "scriptId":"u65"},
    "9222a69203f24dce98da087ef613aee7":{
      "scriptId":"u66"},
    "c2623ea7e1e1445990f85c833269dceb":{
      "scriptId":"u67"},
    "8441155521314d29995963aae5bf5516":{
      "scriptId":"u68"},
    "13dca0519299464984bcfc6ac7058bd1":{
      "scriptId":"u69"},
    "98fb9bbf0c67412991d0b1511d308c59":{
      "scriptId":"u70"},
    "7dbace6c5a3d4e0082664b6e80fb82d1":{
      "scriptId":"u71"},
    "84a281662219451a86e3dd907fac9da3":{
      "scriptId":"u72"},
    "3f9c2abe2e6540f5b3597e7473728a0d":{
      "scriptId":"u73"},
    "4f8b894f8eb24c9b96fe74d58e7ac5a5":{
      "scriptId":"u74"},
    "b4d96452f955411498fa4b7becf3e2ae":{
      "scriptId":"u75"},
    "f679219db48843bcaac91262296cb545":{
      "scriptId":"u76"},
    "bdadef9504f449da84d7ab71faaaea15":{
      "scriptId":"u77"},
    "843a3d864f43464faaa3a4e15b1ba76c":{
      "scriptId":"u78"},
    "0d645085ca8a4dc1bcc0ab01cee3630f":{
      "scriptId":"u79"},
    "e7a3de690c774b62984d3767d96b535e":{
      "scriptId":"u80"},
    "c49674ab12cc4f74a9e42950fd49e35a":{
      "scriptId":"u81"},
    "5378c4eb566c4a1eac953df04ac74ed2":{
      "scriptId":"u82"},
    "33d44a3ea455463f858304930d08abb1":{
      "scriptId":"u83"},
    "e56a70dce504484684582714e0d94770":{
      "scriptId":"u84"},
    "e13d5784f3744e42bb687db70d9bd7a2":{
      "scriptId":"u85"},
    "e1889c93c93f451999c1bb3225c1eea0":{
      "scriptId":"u86"},
    "40f731c85fe54bd7918c675c80daaeb0":{
      "scriptId":"u87"},
    "22af8afc9cf14bc89a318cdbb4681a87":{
      "scriptId":"u88"},
    "185e1c669bbd46e9a143da9803c59a81":{
      "scriptId":"u89"},
    "73b51c8a47c6442992289d996fc52c55":{
      "scriptId":"u90"},
    "8e573a500d9349638fe213706ccb5b94":{
      "scriptId":"u91"},
    "d4bb5c969d1e4fc8bd4f3d7fd35efad3":{
      "scriptId":"u92"},
    "27779bac5d93494cb7e59dafed506074":{
      "scriptId":"u93"},
    "b1ca6b1a709747acb2ffb9c8a80dbf9f":{
      "scriptId":"u94"},
    "349ea80fab8545889a14ab70314406f4":{
      "scriptId":"u95"},
    "4e049243518f4cbd8c04811a2813b0be":{
      "scriptId":"u96"},
    "45bbe37a2e864a1abe4a3354874b0b74":{
      "scriptId":"u97"},
    "d44292d94df44ac1b6759be5f8ba85fe":{
      "scriptId":"u98"}}});