$axure.loadCurrentPage({
  "url":"create_plan.html",
  "generationDate":new Date(1520018786468.7),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"2f4f415b07f24c4e96ff0dc5c3476ace",
    "type":"Axure:Page",
    "name":"Create Plan",
    "notes":{
      "Default":"<p><span>Objectives gets added on the table. Taking into account that the first objective is selected</span></p>"},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"c3f36e5a22c849a5b16f67d58a7bd4e9",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"4bf034ee21ba4a9c88f41f4b11a279dd"},
{
          "id":"3e5f246d213b443a80f7ecb38270364b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF3399CC},
            "location":{
              "x":151,
              "y":117},
            "size":{
              "width":2050,
              "height":1530}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7e506edf6fd4440a87480cae21946a47",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF3399CC},
                "location":{
                  "x":151,
                  "y":117},
                "size":{
                  "width":2050,
                  "height":1530}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/create_plan/u5.png"}},
{
          "id":"7310dd10428148e79a03e7ebeb055963",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":210,
              "y":499},
            "size":{
              "width":1930,
              "height":1091}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"85ed8fe4a0c34c22931691c6a4fcfd18",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":210,
                  "y":499},
                "size":{
                  "width":1930,
                  "height":1091}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/create_plan/u7.png"}},
{
          "id":"87c7c0c2925842948246d4e420ced943",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1698,
              "y":995},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eaa7d3d7b58e450d860801372d5b07ed",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1698,
                  "y":995},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/create_plan/u9.png"}},
{
          "id":"caa7024d3876461fb7b03a0cdeaf7c26",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"48px",
            "location":{
              "x":276,
              "y":615},
            "size":{
              "width":518,
              "height":55}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e62410342e4c4624a1684fa2928b0ed6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"48px",
                "location":{
                  "x":276,
                  "y":615},
                "size":{
                  "width":518,
                  "height":55}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e5d6ce85019e49f7a34cb4f9e2307ae1",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"72px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":777.5,
              "y":188},
            "size":{
              "width":797,
              "height":82},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cb509899dd134135bee0062a77ea53f4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"72px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":777.5,
                  "y":188},
                "size":{
                  "width":797,
                  "height":82},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"aead783fe95c4ced8c407c071b9bba9e",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFF3BF8AC},
{
                  "color":0xFF3BF8AC},
{
                  "color":0xFFE4E4E4},
{
                  "color":0xFFE4E4E4}]},
            "location":{
              "x":230,
              "y":349},
            "size":{
              "width":110,
              "height":110}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6454b6f782c443518e64704e1e34b457",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFF3BF8AC},
{
                      "color":0xFF3BF8AC},
{
                      "color":0xFFE4E4E4},
{
                      "color":0xFFE4E4E4}]},
                "location":{
                  "x":230,
                  "y":349},
                "size":{
                  "width":110,
                  "height":110}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/create_plan/u15.png"}},
{
          "id":"f6608d2a80eb47e3802ff6889afdfb0c",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":275.5,
              "y":385.5},
            "size":{
              "width":19,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"01a5c079c89149f7bb0b893f7b8f5902",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":275.5,
                  "y":385.5},
                "size":{
                  "width":19,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b97a796869544552bae55738b5069971",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":615,
              "y":349},
            "size":{
              "width":110,
              "height":110}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d3042ad9869e435db9d5b3eaa9f09e7b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":615,
                  "y":349},
                "size":{
                  "width":110,
                  "height":110}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/create_plan/u19.png"}},
{
          "id":"a0274d2b0fd747aeaef3d3d56803e8d4",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":661,
              "y":386},
            "size":{
              "width":19,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"656627b9b0d34a46b622f837e049f108",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":661,
                  "y":386},
                "size":{
                  "width":19,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b4eef1caaae94c0faf95d3226b9fa95d",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":1027,
              "y":349},
            "size":{
              "width":110,
              "height":110}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"39f4a9588e70480ba82e8ceb9ebc872b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1027,
                  "y":349},
                "size":{
                  "width":110,
                  "height":110}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/create_plan/u19.png"}},
{
          "id":"5cf892a971b4447790c3eb7564a1fb41",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":1073,
              "y":386},
            "size":{
              "width":19,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"358f29d450de4a7da035c92882f9b56e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1073,
                  "y":386},
                "size":{
                  "width":19,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"88a5ec3856c6405aa9a8004e5e7f41f4",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":1416,
              "y":349},
            "size":{
              "width":110,
              "height":110}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a42699eb78124c37b3257f4fde968745",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1416,
                  "y":349},
                "size":{
                  "width":110,
                  "height":110}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/create_plan/u19.png"}},
{
          "id":"87e798c136284f47b2c307a33d7a0772",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":1462,
              "y":386},
            "size":{
              "width":19,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0fcb7a1feb0345b8a55d46cee78c550f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1462,
                  "y":386},
                "size":{
                  "width":19,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"62006a683ae24256be957daa7c7ccc18",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":1759,
              "y":349},
            "size":{
              "width":110,
              "height":110}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"88b66ed89877492ab57df7fd1be719bb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1759,
                  "y":349},
                "size":{
                  "width":110,
                  "height":110}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/create_plan/u19.png"}},
{
          "id":"ab9ddebb3fbe49feade5930553f4da5c",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":1805,
              "y":386},
            "size":{
              "width":19,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c24848625d5d43598a7b30f713114476",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1805,
                  "y":386},
                "size":{
                  "width":19,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d26127c57be647faa6b85ec96d06af8d",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":2027,
              "y":349},
            "size":{
              "width":110,
              "height":110}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9b365b122e8e42e5ad4e9c8da2dd92a1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":2027,
                  "y":349},
                "size":{
                  "width":110,
                  "height":110}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/create_plan/u19.png"}},
{
          "id":"4a2c3d520a6645bb985cab07f18dc104",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":2073,
              "y":386},
            "size":{
              "width":19,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9ffe667bd47a4b26a47704eef21a13c1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":2073,
                  "y":386},
                "size":{
                  "width":19,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"86c4661ccd344014841a76f1d5871fa9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":892,
              "y":592},
            "size":{
              "width":1068,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"14c46c2d7b2149f9a755bba7c295c6f2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":892,
                  "y":592},
                "size":{
                  "width":1068,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/create_plan/u39.png"}},
{
          "id":"59df81427c444660b07a3773623c5452",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"48px",
            "location":{
              "x":276,
              "y":824},
            "size":{
              "width":319,
              "height":55}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6966ec4cddae4a6884377225cf3e76c6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"48px",
                "location":{
                  "x":276,
                  "y":824},
                "size":{
                  "width":319,
                  "height":55}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a7c1114aa1524d9f83b388102dec068b",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "fontSize":"48px",
            "location":{
              "x":892,
              "y":799},
            "size":{
              "width":588,
              "height":80}},
          "adaptiveStyles":{
}},
{
          "id":"d13c3d6994324f29a5a661a922db4b17",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":214.999984741211,
              "y":199},
            "size":{
              "width":100,
              "height":60},
            "rotation":"270",
            "textRotation":"270"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"253d0c4bf2d143ad85c4f2ba6a2e6d9a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":214.999984741211,
                  "y":199},
                "size":{
                  "width":100,
                  "height":60},
                "rotation":"270",
                "textRotation":"270"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Dashboard in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"dashboard.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/create_plan/u44.png"}},
{
          "id":"8b1bddf4e2b64e388497be98a3f8c916",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"48px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":310,
              "y":204},
            "size":{
              "width":115,
              "height":55}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f02a207dfd5741058510a269432e0624",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"48px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":310,
                  "y":204},
                "size":{
                  "width":115,
                  "height":55}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"233105fdf9ee4c8d8624ae751f597261",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"48px",
            "fill":{
              "fillType":"solid",
              "color":0xFF00CC99},
            "location":{
              "x":1889,
              "y":1410},
            "size":{
              "width":248,
              "height":180},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"470480c791fb411d9cb5b6201436b83f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"48px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF00CC99},
                "location":{
                  "x":1889,
                  "y":1410},
                "size":{
                  "width":248,
                  "height":180},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Monitor KPIs in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"monitor_kpis.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/create_plan/u48.png"}},
{
          "id":"ea4dd619574747bdb6f6aa72409cb0e3",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":773.5,
              "y":960},
            "size":{
              "width":803,
              "height":342}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dbce8ec3e203400faf3f6708a3c14e57",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontSize":"48px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "size":{
                  "width":401,
                  "height":114}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"519578cf79354ecca7f583435658e035",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"48px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "size":{
                      "width":401,
                      "height":114}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/create_plan/u51.png"}},
{
              "id":"caa18e857e7549739bdbc06e2bc45afe",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontSize":"48px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":401,
                  "y":0},
                "size":{
                  "width":402,
                  "height":114}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ac3f850f531a43ae95e190ada13b181b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"48px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":401,
                      "y":0},
                    "size":{
                      "width":402,
                      "height":114}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/create_plan/u53.png"}},
{
              "id":"f03525809e794d18aa0950ff1e62b7a7",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontSize":"48px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":114},
                "size":{
                  "width":401,
                  "height":114}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"8918f1e29b10471fb5aceba10c593b32",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"48px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":114},
                    "size":{
                      "width":401,
                      "height":114}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/create_plan/u51.png"}},
{
              "id":"477591a894fb4a63b845a9ce427376b1",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontSize":"48px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":401,
                  "y":114},
                "size":{
                  "width":402,
                  "height":114}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"27931d307861487ba915df62f05392a0",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"48px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":401,
                      "y":114},
                    "size":{
                      "width":402,
                      "height":114}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/create_plan/u53.png"}},
{
              "id":"0d84ac0130c14d9fa2023b7ef8f83f6d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontSize":"48px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":228},
                "size":{
                  "width":401,
                  "height":114}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ed03df62a3f14a879e43ac3ece6f1e2e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"48px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":228},
                    "size":{
                      "width":401,
                      "height":114}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/create_plan/u59.png"}},
{
              "id":"b740101e10004ba79fd4e97d32308624",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontSize":"48px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":401,
                  "y":228},
                "size":{
                  "width":402,
                  "height":114}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"241f72f973e946bab9d0456e9616fcbc",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"48px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":401,
                      "y":228},
                    "size":{
                      "width":402,
                      "height":114}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/create_plan/u61.png"}}]},
{
          "id":"ac7e440d77c04d20bc2c2ff6abd4e3f7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"48px",
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":1712,
              "y":799},
            "size":{
              "width":248,
              "height":78},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"87ae1f15472741838b48696293e38fa6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"48px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":1712,
                  "y":799},
                "size":{
                  "width":248,
                  "height":78},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/create_plan/u63.png"}},
{
          "id":"9963dc7bb2c340ab9a43fc0cbe2e081c",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"48px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":684,
              "y":1335},
            "size":{
              "width":983,
              "height":55}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cc1d9944ad724163a47cd61f0dc4be35",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"48px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":684,
                  "y":1335},
                "size":{
                  "width":983,
                  "height":55}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"908d101e86344638b3eea7f0a730c1f4",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Regular', 'Arial'",
            "fontSize":"48px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":2490,
              "y":404},
            "size":{
              "width":780,
              "height":456}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"281e451353b84f7ebbc2d9dde3162056",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Regular', 'Arial'",
                "fontSize":"48px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":2490,
                  "y":404},
                "size":{
                  "width":780,
                  "height":456}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d4eda76f41f241fa8243184df113ed2f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1635,
              "y":990},
            "size":{
              "width":55,
              "height":55},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCC0033}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f682d864caf84aca958ac424c4ab3c5f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1635,
                  "y":990},
                "size":{
                  "width":55,
                  "height":55},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCC0033}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/create_plan/u69.png"}},
{
          "id":"fe256755e42d48f09927f7b1185c9949",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":1635,
              "y":1037},
            "size":{
              "width":100,
              "height":13},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ec5c752de3fb4f67bfbc999065a08637",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":1635,
                  "y":1037},
                "size":{
                  "width":100,
                  "height":13},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/create_plan/u71.png"}},
{
          "id":"3378ffd431704561b028a8243161b992",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1698,
              "y":1101},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"271a983ce9d5443595823d5470b843e8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1698,
                  "y":1101},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/create_plan/u9.png"}},
{
          "id":"e2370f3c2bdc4531ae18396e496c0ec6",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1635,
              "y":1096},
            "size":{
              "width":55,
              "height":55},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCC0033}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d9bed1c3f5cf48ebae4b3af7c78a839d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1635,
                  "y":1096},
                "size":{
                  "width":55,
                  "height":55},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCC0033}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/create_plan/u69.png"}},
{
          "id":"306fa700f6434bbb8a6769868f81d01f",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":1635,
              "y":1143},
            "size":{
              "width":100,
              "height":13},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"43e3af89491c417ea038966bae40b9c1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":1635,
                  "y":1143},
                "size":{
                  "width":100,
                  "height":13},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/create_plan/u71.png"}}]}},
  "masters":{
    "4bf034ee21ba4a9c88f41f4b11a279dd":{
      "packageId":"4bf034ee21ba4a9c88f41f4b11a279dd",
      "type":"Axure:Master",
      "name":"ipad",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"b7fd228ad5a240279ab302aee1b87b52",
            "label":"",
            "type":"flowShape",
            "styleType":"flowShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF333333},
              "size":{
                "width":2352,
                "height":1764},
              "borderFill":{
                "fillType":"linearGradient",
                "colors":[{
                    "color":0xFF000099},
{
                    "color":0xFF000099},
{
                    "color":0xFF000000},
{
                    "color":0xFF000000}]}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"2bfa5c8614094fb287d60d7d12e45ee2",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF333333},
                  "size":{
                    "width":2352,
                    "height":1764},
                  "borderFill":{
                    "fillType":"linearGradient",
                    "colors":[{
                        "color":0xFF000099},
{
                        "color":0xFF000099},
{
                        "color":0xFF000000},
{
                        "color":0xFF000000}]}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/low_fi_index/u1.png"}},
{
            "id":"fc15c73249d34b269969db2b09f4acef",
            "label":"",
            "type":"flowShape",
            "styleType":"flowShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"linearGradient",
                "colors":[{
                    "color":0xFFFFFFFF},
{
                    "color":0xFFFFFFFF},
{
                    "color":0xFFE4E4E4},
{
                    "color":0xFFE4E4E4}]},
              "location":{
                "x":152,
                "y":114},
              "size":{
                "width":2048,
                "height":1536}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"4bb6471cc35846dab73c365841f3ef41",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"linearGradient",
                    "colors":[{
                        "color":0xFFFFFFFF},
{
                        "color":0xFFFFFFFF},
{
                        "color":0xFFE4E4E4},
{
                        "color":0xFFE4E4E4}]},
                  "location":{
                    "x":152,
                    "y":114},
                  "size":{
                    "width":2048,
                    "height":1536}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/low_fi_index/u3.png"}}]}}},
  "objectPaths":{
    "c3f36e5a22c849a5b16f67d58a7bd4e9":{
      "scriptId":"u0",
      "b7fd228ad5a240279ab302aee1b87b52":{
        "scriptId":"u1"},
      "2bfa5c8614094fb287d60d7d12e45ee2":{
        "scriptId":"u2"},
      "fc15c73249d34b269969db2b09f4acef":{
        "scriptId":"u3"},
      "4bb6471cc35846dab73c365841f3ef41":{
        "scriptId":"u4"}},
    "3e5f246d213b443a80f7ecb38270364b":{
      "scriptId":"u5"},
    "7e506edf6fd4440a87480cae21946a47":{
      "scriptId":"u6"},
    "7310dd10428148e79a03e7ebeb055963":{
      "scriptId":"u7"},
    "85ed8fe4a0c34c22931691c6a4fcfd18":{
      "scriptId":"u8"},
    "87c7c0c2925842948246d4e420ced943":{
      "scriptId":"u9"},
    "eaa7d3d7b58e450d860801372d5b07ed":{
      "scriptId":"u10"},
    "caa7024d3876461fb7b03a0cdeaf7c26":{
      "scriptId":"u11"},
    "e62410342e4c4624a1684fa2928b0ed6":{
      "scriptId":"u12"},
    "e5d6ce85019e49f7a34cb4f9e2307ae1":{
      "scriptId":"u13"},
    "cb509899dd134135bee0062a77ea53f4":{
      "scriptId":"u14"},
    "aead783fe95c4ced8c407c071b9bba9e":{
      "scriptId":"u15"},
    "6454b6f782c443518e64704e1e34b457":{
      "scriptId":"u16"},
    "f6608d2a80eb47e3802ff6889afdfb0c":{
      "scriptId":"u17"},
    "01a5c079c89149f7bb0b893f7b8f5902":{
      "scriptId":"u18"},
    "b97a796869544552bae55738b5069971":{
      "scriptId":"u19"},
    "d3042ad9869e435db9d5b3eaa9f09e7b":{
      "scriptId":"u20"},
    "a0274d2b0fd747aeaef3d3d56803e8d4":{
      "scriptId":"u21"},
    "656627b9b0d34a46b622f837e049f108":{
      "scriptId":"u22"},
    "b4eef1caaae94c0faf95d3226b9fa95d":{
      "scriptId":"u23"},
    "39f4a9588e70480ba82e8ceb9ebc872b":{
      "scriptId":"u24"},
    "5cf892a971b4447790c3eb7564a1fb41":{
      "scriptId":"u25"},
    "358f29d450de4a7da035c92882f9b56e":{
      "scriptId":"u26"},
    "88a5ec3856c6405aa9a8004e5e7f41f4":{
      "scriptId":"u27"},
    "a42699eb78124c37b3257f4fde968745":{
      "scriptId":"u28"},
    "87e798c136284f47b2c307a33d7a0772":{
      "scriptId":"u29"},
    "0fcb7a1feb0345b8a55d46cee78c550f":{
      "scriptId":"u30"},
    "62006a683ae24256be957daa7c7ccc18":{
      "scriptId":"u31"},
    "88b66ed89877492ab57df7fd1be719bb":{
      "scriptId":"u32"},
    "ab9ddebb3fbe49feade5930553f4da5c":{
      "scriptId":"u33"},
    "c24848625d5d43598a7b30f713114476":{
      "scriptId":"u34"},
    "d26127c57be647faa6b85ec96d06af8d":{
      "scriptId":"u35"},
    "9b365b122e8e42e5ad4e9c8da2dd92a1":{
      "scriptId":"u36"},
    "4a2c3d520a6645bb985cab07f18dc104":{
      "scriptId":"u37"},
    "9ffe667bd47a4b26a47704eef21a13c1":{
      "scriptId":"u38"},
    "86c4661ccd344014841a76f1d5871fa9":{
      "scriptId":"u39"},
    "14c46c2d7b2149f9a755bba7c295c6f2":{
      "scriptId":"u40"},
    "59df81427c444660b07a3773623c5452":{
      "scriptId":"u41"},
    "6966ec4cddae4a6884377225cf3e76c6":{
      "scriptId":"u42"},
    "a7c1114aa1524d9f83b388102dec068b":{
      "scriptId":"u43"},
    "d13c3d6994324f29a5a661a922db4b17":{
      "scriptId":"u44"},
    "253d0c4bf2d143ad85c4f2ba6a2e6d9a":{
      "scriptId":"u45"},
    "8b1bddf4e2b64e388497be98a3f8c916":{
      "scriptId":"u46"},
    "f02a207dfd5741058510a269432e0624":{
      "scriptId":"u47"},
    "233105fdf9ee4c8d8624ae751f597261":{
      "scriptId":"u48"},
    "470480c791fb411d9cb5b6201436b83f":{
      "scriptId":"u49"},
    "ea4dd619574747bdb6f6aa72409cb0e3":{
      "scriptId":"u50"},
    "dbce8ec3e203400faf3f6708a3c14e57":{
      "scriptId":"u51"},
    "519578cf79354ecca7f583435658e035":{
      "scriptId":"u52"},
    "caa18e857e7549739bdbc06e2bc45afe":{
      "scriptId":"u53"},
    "ac3f850f531a43ae95e190ada13b181b":{
      "scriptId":"u54"},
    "f03525809e794d18aa0950ff1e62b7a7":{
      "scriptId":"u55"},
    "8918f1e29b10471fb5aceba10c593b32":{
      "scriptId":"u56"},
    "477591a894fb4a63b845a9ce427376b1":{
      "scriptId":"u57"},
    "27931d307861487ba915df62f05392a0":{
      "scriptId":"u58"},
    "0d84ac0130c14d9fa2023b7ef8f83f6d":{
      "scriptId":"u59"},
    "ed03df62a3f14a879e43ac3ece6f1e2e":{
      "scriptId":"u60"},
    "b740101e10004ba79fd4e97d32308624":{
      "scriptId":"u61"},
    "241f72f973e946bab9d0456e9616fcbc":{
      "scriptId":"u62"},
    "ac7e440d77c04d20bc2c2ff6abd4e3f7":{
      "scriptId":"u63"},
    "87ae1f15472741838b48696293e38fa6":{
      "scriptId":"u64"},
    "9963dc7bb2c340ab9a43fc0cbe2e081c":{
      "scriptId":"u65"},
    "cc1d9944ad724163a47cd61f0dc4be35":{
      "scriptId":"u66"},
    "908d101e86344638b3eea7f0a730c1f4":{
      "scriptId":"u67"},
    "281e451353b84f7ebbc2d9dde3162056":{
      "scriptId":"u68"},
    "d4eda76f41f241fa8243184df113ed2f":{
      "scriptId":"u69"},
    "f682d864caf84aca958ac424c4ab3c5f":{
      "scriptId":"u70"},
    "fe256755e42d48f09927f7b1185c9949":{
      "scriptId":"u71"},
    "ec5c752de3fb4f67bfbc999065a08637":{
      "scriptId":"u72"},
    "3378ffd431704561b028a8243161b992":{
      "scriptId":"u73"},
    "271a983ce9d5443595823d5470b843e8":{
      "scriptId":"u74"},
    "e2370f3c2bdc4531ae18396e496c0ec6":{
      "scriptId":"u75"},
    "d9bed1c3f5cf48ebae4b3af7c78a839d":{
      "scriptId":"u76"},
    "306fa700f6434bbb8a6769868f81d01f":{
      "scriptId":"u77"},
    "43e3af89491c417ea038966bae40b9c1":{
      "scriptId":"u78"}}});