$axure.loadCurrentPage({
  "url":"monitor_kpis.html",
  "generationDate":new Date(1520009245760.17),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"bbdd0bdd35a3475988ba32e7a5fe4d0d",
    "type":"Axure:Page",
    "name":"Monitor KPIs",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"3768c5a298344df8950306a22206dffc",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"4bf034ee21ba4a9c88f41f4b11a279dd"},
{
          "id":"17e9f37119394ce08dfe7de50ed1ab53",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF3399CC},
            "location":{
              "x":151,
              "y":117},
            "size":{
              "width":2050,
              "height":1530}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"243cea0a28394b178a477c3350bca2e8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF3399CC},
                "location":{
                  "x":151,
                  "y":117},
                "size":{
                  "width":2050,
                  "height":1530}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/create_plan/u5.png"}},
{
          "id":"5630750963cc4158b6da0f485d904d33",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":210,
              "y":499},
            "size":{
              "width":1930,
              "height":1091}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c8695e4680484fa6892b1605141b133f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":210,
                  "y":499},
                "size":{
                  "width":1930,
                  "height":1091}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/create_plan/u7.png"}},
{
          "id":"9734b3975f8b4db6810f535d8248210c",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"48px",
            "location":{
              "x":276,
              "y":560},
            "size":{
              "width":213,
              "height":55}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3cc34f7536e84936bfdd38f1da44face",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"48px",
                "location":{
                  "x":276,
                  "y":560},
                "size":{
                  "width":213,
                  "height":55}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5bb6e1d9a2dc4b4d84b758cc1f539176",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"72px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":778,
              "y":188},
            "size":{
              "width":797,
              "height":82},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6e99de44d42e4a568800136674dcad02",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"72px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":778,
                  "y":188},
                "size":{
                  "width":797,
                  "height":82},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9cb1db958b97492781029c6ad485a1ef",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFF00FF99},
{
                  "color":0xFF00FF99},
{
                  "color":0xFFE4E4E4},
{
                  "color":0xFFE4E4E4}]},
            "location":{
              "x":230,
              "y":349},
            "size":{
              "width":110,
              "height":110}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"36bf0332d9a645cc91e60e28fe706063",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFF00FF99},
{
                      "color":0xFF00FF99},
{
                      "color":0xFFE4E4E4},
{
                      "color":0xFFE4E4E4}]},
                "location":{
                  "x":230,
                  "y":349},
                "size":{
                  "width":110,
                  "height":110}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Create Plan in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"create_plan.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/monitor_kpis/u13.png"}},
{
          "id":"115afe26c38e449689341e33346b33de",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":276,
              "y":386},
            "size":{
              "width":19,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"67c3a53db08848e5a1317c580ece2c14",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":276,
                  "y":386},
                "size":{
                  "width":19,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7e769d6e18b94509927172d199392043",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFF3BF8AC},
{
                  "color":0xFF3BF8AC},
{
                  "color":0xFFE4E4E4},
{
                  "color":0xFFE4E4E4}]},
            "location":{
              "x":615,
              "y":349},
            "size":{
              "width":110,
              "height":110}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"17ca2730b08a473bbd39d0d182c0dd41",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFF3BF8AC},
{
                      "color":0xFF3BF8AC},
{
                      "color":0xFFE4E4E4},
{
                      "color":0xFFE4E4E4}]},
                "location":{
                  "x":615,
                  "y":349},
                "size":{
                  "width":110,
                  "height":110}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/create_plan/u15.png"}},
{
          "id":"e8f0529189ef4332bdcbb992586a89c5",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":661,
              "y":386},
            "size":{
              "width":19,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5672e249cc6542e0af685de63f9b6bc3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":661,
                  "y":386},
                "size":{
                  "width":19,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f81cb08c8e0241fe95f59c6dd8d8ad14",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":1027,
              "y":349},
            "size":{
              "width":110,
              "height":110}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"431ee0ac7b354103a145c77aa0c5c990",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1027,
                  "y":349},
                "size":{
                  "width":110,
                  "height":110}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/create_plan/u19.png"}},
{
          "id":"72eb24529a284df0a485701f5f8a8b67",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":1073,
              "y":386},
            "size":{
              "width":19,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c0185520c8274faa8d1829a24144941d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1073,
                  "y":386},
                "size":{
                  "width":19,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2a7013f56c9f4ee3b0f60fd4b197aef3",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":1416,
              "y":349},
            "size":{
              "width":110,
              "height":110}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"828c3d20c01c4f6b910911b9dd8e3edf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1416,
                  "y":349},
                "size":{
                  "width":110,
                  "height":110}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/create_plan/u19.png"}},
{
          "id":"bd51bbd62d9d4d20b8bdc3608ba62021",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":1462,
              "y":386},
            "size":{
              "width":19,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"685bac88238b4baeb222a5894bff364f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1462,
                  "y":386},
                "size":{
                  "width":19,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a7ef1982f4a94d06976d3c8b78602d42",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":1759,
              "y":349},
            "size":{
              "width":110,
              "height":110}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"72ad685e9d064ddba7a08640c85a6661",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1759,
                  "y":349},
                "size":{
                  "width":110,
                  "height":110}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/create_plan/u19.png"}},
{
          "id":"0bdc5f1de41547d5b7b3afa93bf37b4e",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":1805,
              "y":386},
            "size":{
              "width":19,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a7882ab2a5734023ae0fe7dde5c2542e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1805,
                  "y":386},
                "size":{
                  "width":19,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4972d36340994a2996a074c63a7cfe0e",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":2027,
              "y":349},
            "size":{
              "width":110,
              "height":110}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7b4c6de65f82456c828338c0f1bb3f14",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":2027,
                  "y":349},
                "size":{
                  "width":110,
                  "height":110}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/create_plan/u19.png"}},
{
          "id":"d932c48a4bc541eb91eaa08b5c1044bf",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":2073,
              "y":386},
            "size":{
              "width":19,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"56b37dfc67574569a542c3afd0315b6f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":2073,
                  "y":386},
                "size":{
                  "width":19,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"11b44755c2ab4f759f95b0a6f68c34c4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"48px",
            "fill":{
              "fillType":"solid",
              "color":0xFF00CC99},
            "location":{
              "x":1892,
              "y":1410},
            "size":{
              "width":248,
              "height":180},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8197aff019e5479582b820e7d8c83320",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"48px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF00CC99},
                "location":{
                  "x":1892,
                  "y":1410},
                "size":{
                  "width":248,
                  "height":180},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Risks in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"risks.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/create_plan/u48.png"}},
{
          "id":"a56c737d72a14b28a1518537126d3381",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":276,
              "y":794},
            "size":{
              "width":614,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7b0eec10999f4e56bce399b7828aba51",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":276,
                  "y":794},
                "size":{
                  "width":614,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/monitor_kpis/u39.png"}},
{
          "id":"0286b10578d24301b4a6197f4ea48d3e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":276,
              "y":928},
            "size":{
              "width":404,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3fd0a72d703b40d2ac99d8dc2adba8be",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":276,
                  "y":928},
                "size":{
                  "width":404,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/monitor_kpis/u41.png"}},
{
          "id":"f12ed41136454a418c5b7410fbf0bee3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":276,
              "y":1144},
            "size":{
              "width":404,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ade3a678400c41d689198b58beef7f4f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":276,
                  "y":1144},
                "size":{
                  "width":404,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/monitor_kpis/u41.png"}},
{
          "id":"9fd43eca527e4c7bbe693c335d12b2f1",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"36px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":325,
              "y":824},
            "size":{
              "width":294,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2a78408fc1424fefa31f9262c7b00d5d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"36px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":325,
                  "y":824},
                "size":{
                  "width":294,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"196f48a3eea1427cac7dcb31aa38c0cf",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"36px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":325,
              "y":953},
            "size":{
              "width":338,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"988da03d435a40bcbe6278d7308e0c3b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"36px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":325,
                  "y":953},
                "size":{
                  "width":338,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0796f35389b4444d88199b37bf23b2a7",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"36px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":325,
              "y":1172},
            "size":{
              "width":287,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a6631d06b16641d590e1ae039f9a5317",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"36px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":325,
                  "y":1172},
                "size":{
                  "width":287,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9f029671a5da4436864e75032e754e25",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1715,
              "y":560},
            "size":{
              "width":377,
              "height":377}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"94f80c3adb4842c99e68a0fac359798c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1715,
                  "y":560},
                "size":{
                  "width":377,
                  "height":377}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/monitor_kpis/u51.png"}},
{
          "id":"45f396b02bf04d3889324774e5f1dcb1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1645,
              "y":867},
            "size":{
              "width":378,
              "height":100},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"07e004c7b3c04cb78e854717c29df993",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1645,
                  "y":867},
                "size":{
                  "width":378,
                  "height":100},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/monitor_kpis/u53.png"}},
{
          "id":"1491aad1b00e4afeb6e6b9f30b9a3938",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"48px",
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":276,
              "y":1396},
            "size":{
              "width":248,
              "height":78},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"069be61b75324cf9b5722dccd8df6a20",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"48px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":276,
                  "y":1396},
                "size":{
                  "width":248,
                  "height":78},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/create_plan/u63.png"}},
{
          "id":"976e0358b4c94e6e92e5515276ec4b7f",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":974,
              "y":885},
            "size":{
              "width":756,
              "height":547}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0f9a0f5db24f4680a7b31b03ed23db10",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontSize":"36px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "size":{
                  "width":262,
                  "height":86}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0ddbc8aa2ef34404bef27e6c718c8d62",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"36px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "size":{
                      "width":262,
                      "height":86}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/monitor_kpis/u58.png"}},
{
              "id":"64cf40bc3e7248e2a452456cc193e03d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontSize":"36px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":258},
                "size":{
                  "width":262,
                  "height":289}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ff27a9f3f24343f1a4836870a9b46181",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"36px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":258},
                    "size":{
                      "width":262,
                      "height":289}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/monitor_kpis/u76.png"}},
{
              "id":"6b00fad06c8f4f4cb410c3489ec6bb4f",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontSize":"36px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":262,
                  "y":0},
                "size":{
                  "width":242,
                  "height":86}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"411345f3767e4a0199b8b19956c847a5",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"36px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":262,
                      "y":0},
                    "size":{
                      "width":242,
                      "height":86}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/monitor_kpis/u60.png"}},
{
              "id":"646bce2d0f4c4f7a89f7cd8be97680e8",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontSize":"36px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":262,
                  "y":258},
                "size":{
                  "width":242,
                  "height":289}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"9b6bc3334ef74ec59fa43c184cfe4ad2",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"36px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":262,
                      "y":258},
                    "size":{
                      "width":242,
                      "height":289}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/monitor_kpis/u78.png"}},
{
              "id":"48c5abfd67cf486792bbdc44d1001f12",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontSize":"36px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":504,
                  "y":0},
                "size":{
                  "width":252,
                  "height":86}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"19ef8d72ef4243f2904d4227fb4d6244",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"36px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":504,
                      "y":0},
                    "size":{
                      "width":252,
                      "height":86}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/monitor_kpis/u62.png"}},
{
              "id":"3220bc1064184af282ce89a39af5908d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontSize":"36px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":504,
                  "y":258},
                "size":{
                  "width":252,
                  "height":289}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"68d9afd944f04acdbf30ddb8f5acfdca",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"36px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":504,
                      "y":258},
                    "size":{
                      "width":252,
                      "height":289}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/monitor_kpis/u80.png"}},
{
              "id":"1646c159277147c69415c5270d09369d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontSize":"36px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":86},
                "size":{
                  "width":262,
                  "height":86}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"5c30de87357f4c8caf54972f92c2f94b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"36px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":86},
                    "size":{
                      "width":262,
                      "height":86}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/monitor_kpis/u58.png"}},
{
              "id":"93e44a04c26e4ea2876fd278b8f27f8a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontSize":"36px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":262,
                  "y":86},
                "size":{
                  "width":242,
                  "height":86}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"6ffe23d646d44e97a09edfebc1e45d22",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"36px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":262,
                      "y":86},
                    "size":{
                      "width":242,
                      "height":86}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/monitor_kpis/u60.png"}},
{
              "id":"c855801cb6694903b47d182133efb1eb",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontSize":"36px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":504,
                  "y":86},
                "size":{
                  "width":252,
                  "height":86}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"36dfdaf635994ac99b9eb0878af8f935",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"36px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":504,
                      "y":86},
                    "size":{
                      "width":252,
                      "height":86}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/monitor_kpis/u62.png"}},
{
              "id":"b3513f419881436992a65322254d082b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontSize":"36px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":172},
                "size":{
                  "width":262,
                  "height":86}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"93e980ac3cbc44a98434241dad4ad2cb",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"36px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":172},
                    "size":{
                      "width":262,
                      "height":86}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/monitor_kpis/u58.png"}},
{
              "id":"80126955920b48eba0b008078cfbeeb1",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontSize":"36px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":262,
                  "y":172},
                "size":{
                  "width":242,
                  "height":86}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"8af3acb43ae247ffa473f6ac7312054a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"36px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":262,
                      "y":172},
                    "size":{
                      "width":242,
                      "height":86}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/monitor_kpis/u60.png"}},
{
              "id":"d7a4b8c095214f5ab1ded2682f4eb445",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontSize":"36px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":504,
                  "y":172},
                "size":{
                  "width":252,
                  "height":86}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0b1a436a3d314c19b825eaffbe38aa15",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"36px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":504,
                      "y":172},
                    "size":{
                      "width":252,
                      "height":86}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/monitor_kpis/u62.png"}}]},
{
          "id":"aa656fd90d3e4db78cfa114137c88bb5",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"36px",
            "location":{
              "x":1552,
              "y":898},
            "size":{
              "width":80,
              "height":41}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"701d2c34b6e5472e911de5f4365e22bc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"36px",
                "location":{
                  "x":1552,
                  "y":898},
                "size":{
                  "width":80,
                  "height":41}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6610ed86212643ab981ab1c4c002cc57",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"36px",
            "location":{
              "x":1265,
              "y":898},
            "size":{
              "width":131,
              "height":41}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"76ac7e5f699d4535aaa54042742cada7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"36px",
                "location":{
                  "x":1265,
                  "y":898},
                "size":{
                  "width":131,
                  "height":41}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7df47d4a10374bc19bf574c77f5f600d",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":276,
              "y":1071},
            "size":{
              "width":404,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/monitor_kpis/u86_line.png"}},
{
          "id":"e2d7bd981a414dd3a5048d4b86624469",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":360,
              "y":1046},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d5a2a12cb25943509d593c21619efd16",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":360,
                  "y":1046},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/monitor_kpis/u87.png"}},
{
          "id":"f530013f8fd243d18a9a6db7761bd2ee",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":276,
              "y":1306},
            "size":{
              "width":404,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/monitor_kpis/u86_line.png"}},
{
          "id":"c82dee0519c246aeb123181562fc0dd8",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":512,
              "y":1281},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"39e604f90fb24478a3fd9bf37f07d443",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":512,
                  "y":1281},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/monitor_kpis/u87.png"}},
{
          "id":"437a3cae20d042acb1a78a1a47426bba",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":276,
              "y":661},
            "size":{
              "width":614,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3c7189054a6d402e968efd6dd474ac5e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":276,
                  "y":661},
                "size":{
                  "width":614,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/monitor_kpis/u39.png"}},
{
          "id":"0c5a92f0a9df45b3bfc3c80a4d3fb20f",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"36px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":325,
              "y":691},
            "size":{
              "width":168,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7110484d235b4f7294fcd406b3d8caeb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"36px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":325,
                  "y":691},
                "size":{
                  "width":168,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4c57c3a2292e4c68bdbb71575ff26d0b",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"36px",
            "location":{
              "x":998,
              "y":898},
            "size":{
              "width":168,
              "height":41}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7afce7e45f124c04987b1acfac9f46f6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"36px",
                "location":{
                  "x":998,
                  "y":898},
                "size":{
                  "width":168,
                  "height":41}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0756abb329454cf8993fd7f77c73513e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1840.5,
              "y":982},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"91ef90e7f3b64ffd8d19d1d42b308cf5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1840.5,
                  "y":982},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/create_plan/u9.png"}},
{
          "id":"da4f1e98c75e40e8a22d8f397bccc51e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1777.5,
              "y":977},
            "size":{
              "width":55,
              "height":55},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCC0033}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9cec653d7e584265a8b0939a35722939",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1777.5,
                  "y":977},
                "size":{
                  "width":55,
                  "height":55},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCC0033}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/create_plan/u69.png"}},
{
          "id":"0829b845885847128c9c15a24ea2b995",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":1777.5,
              "y":1024},
            "size":{
              "width":100,
              "height":13},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7b48842db6084177ae5e4fee8fef70bb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":1777.5,
                  "y":1024},
                "size":{
                  "width":100,
                  "height":13},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/create_plan/u71.png"}},
{
          "id":"fbfd3400929d47f4a58d1889a60226cf",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1840,
              "y":1083},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c98d9700209e4e679ff7a048d7f0ffe8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1840,
                  "y":1083},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/create_plan/u9.png"}},
{
          "id":"be53c5be401943c9a13048ebaedcdffc",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1778,
              "y":1078},
            "size":{
              "width":55,
              "height":55},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCC0033}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"808008dec0a94415a9997e8409fb097b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1778,
                  "y":1078},
                "size":{
                  "width":55,
                  "height":55},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCC0033}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/create_plan/u69.png"}},
{
          "id":"298277f5f9f8491698330ccc6614a633",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":1778,
              "y":1125},
            "size":{
              "width":100,
              "height":13},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c5388ec6a6a743cbb886bcf147d2de4e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":1778,
                  "y":1125},
                "size":{
                  "width":100,
                  "height":13},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/create_plan/u71.png"}}]}},
  "masters":{
    "4bf034ee21ba4a9c88f41f4b11a279dd":{
      "packageId":"4bf034ee21ba4a9c88f41f4b11a279dd",
      "type":"Axure:Master",
      "name":"ipad",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"b7fd228ad5a240279ab302aee1b87b52",
            "label":"",
            "type":"flowShape",
            "styleType":"flowShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF333333},
              "size":{
                "width":2352,
                "height":1764},
              "borderFill":{
                "fillType":"linearGradient",
                "colors":[{
                    "color":0xFF000099},
{
                    "color":0xFF000099},
{
                    "color":0xFF000000},
{
                    "color":0xFF000000}]}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"2bfa5c8614094fb287d60d7d12e45ee2",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF333333},
                  "size":{
                    "width":2352,
                    "height":1764},
                  "borderFill":{
                    "fillType":"linearGradient",
                    "colors":[{
                        "color":0xFF000099},
{
                        "color":0xFF000099},
{
                        "color":0xFF000000},
{
                        "color":0xFF000000}]}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/low_fi_index/u1.png"}},
{
            "id":"fc15c73249d34b269969db2b09f4acef",
            "label":"",
            "type":"flowShape",
            "styleType":"flowShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"linearGradient",
                "colors":[{
                    "color":0xFFFFFFFF},
{
                    "color":0xFFFFFFFF},
{
                    "color":0xFFE4E4E4},
{
                    "color":0xFFE4E4E4}]},
              "location":{
                "x":152,
                "y":114},
              "size":{
                "width":2048,
                "height":1536}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"4bb6471cc35846dab73c365841f3ef41",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"linearGradient",
                    "colors":[{
                        "color":0xFFFFFFFF},
{
                        "color":0xFFFFFFFF},
{
                        "color":0xFFE4E4E4},
{
                        "color":0xFFE4E4E4}]},
                  "location":{
                    "x":152,
                    "y":114},
                  "size":{
                    "width":2048,
                    "height":1536}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/low_fi_index/u3.png"}}]}}},
  "objectPaths":{
    "3768c5a298344df8950306a22206dffc":{
      "scriptId":"u0",
      "b7fd228ad5a240279ab302aee1b87b52":{
        "scriptId":"u1"},
      "2bfa5c8614094fb287d60d7d12e45ee2":{
        "scriptId":"u2"},
      "fc15c73249d34b269969db2b09f4acef":{
        "scriptId":"u3"},
      "4bb6471cc35846dab73c365841f3ef41":{
        "scriptId":"u4"}},
    "17e9f37119394ce08dfe7de50ed1ab53":{
      "scriptId":"u5"},
    "243cea0a28394b178a477c3350bca2e8":{
      "scriptId":"u6"},
    "5630750963cc4158b6da0f485d904d33":{
      "scriptId":"u7"},
    "c8695e4680484fa6892b1605141b133f":{
      "scriptId":"u8"},
    "9734b3975f8b4db6810f535d8248210c":{
      "scriptId":"u9"},
    "3cc34f7536e84936bfdd38f1da44face":{
      "scriptId":"u10"},
    "5bb6e1d9a2dc4b4d84b758cc1f539176":{
      "scriptId":"u11"},
    "6e99de44d42e4a568800136674dcad02":{
      "scriptId":"u12"},
    "9cb1db958b97492781029c6ad485a1ef":{
      "scriptId":"u13"},
    "36bf0332d9a645cc91e60e28fe706063":{
      "scriptId":"u14"},
    "115afe26c38e449689341e33346b33de":{
      "scriptId":"u15"},
    "67c3a53db08848e5a1317c580ece2c14":{
      "scriptId":"u16"},
    "7e769d6e18b94509927172d199392043":{
      "scriptId":"u17"},
    "17ca2730b08a473bbd39d0d182c0dd41":{
      "scriptId":"u18"},
    "e8f0529189ef4332bdcbb992586a89c5":{
      "scriptId":"u19"},
    "5672e249cc6542e0af685de63f9b6bc3":{
      "scriptId":"u20"},
    "f81cb08c8e0241fe95f59c6dd8d8ad14":{
      "scriptId":"u21"},
    "431ee0ac7b354103a145c77aa0c5c990":{
      "scriptId":"u22"},
    "72eb24529a284df0a485701f5f8a8b67":{
      "scriptId":"u23"},
    "c0185520c8274faa8d1829a24144941d":{
      "scriptId":"u24"},
    "2a7013f56c9f4ee3b0f60fd4b197aef3":{
      "scriptId":"u25"},
    "828c3d20c01c4f6b910911b9dd8e3edf":{
      "scriptId":"u26"},
    "bd51bbd62d9d4d20b8bdc3608ba62021":{
      "scriptId":"u27"},
    "685bac88238b4baeb222a5894bff364f":{
      "scriptId":"u28"},
    "a7ef1982f4a94d06976d3c8b78602d42":{
      "scriptId":"u29"},
    "72ad685e9d064ddba7a08640c85a6661":{
      "scriptId":"u30"},
    "0bdc5f1de41547d5b7b3afa93bf37b4e":{
      "scriptId":"u31"},
    "a7882ab2a5734023ae0fe7dde5c2542e":{
      "scriptId":"u32"},
    "4972d36340994a2996a074c63a7cfe0e":{
      "scriptId":"u33"},
    "7b4c6de65f82456c828338c0f1bb3f14":{
      "scriptId":"u34"},
    "d932c48a4bc541eb91eaa08b5c1044bf":{
      "scriptId":"u35"},
    "56b37dfc67574569a542c3afd0315b6f":{
      "scriptId":"u36"},
    "11b44755c2ab4f759f95b0a6f68c34c4":{
      "scriptId":"u37"},
    "8197aff019e5479582b820e7d8c83320":{
      "scriptId":"u38"},
    "a56c737d72a14b28a1518537126d3381":{
      "scriptId":"u39"},
    "7b0eec10999f4e56bce399b7828aba51":{
      "scriptId":"u40"},
    "0286b10578d24301b4a6197f4ea48d3e":{
      "scriptId":"u41"},
    "3fd0a72d703b40d2ac99d8dc2adba8be":{
      "scriptId":"u42"},
    "f12ed41136454a418c5b7410fbf0bee3":{
      "scriptId":"u43"},
    "ade3a678400c41d689198b58beef7f4f":{
      "scriptId":"u44"},
    "9fd43eca527e4c7bbe693c335d12b2f1":{
      "scriptId":"u45"},
    "2a78408fc1424fefa31f9262c7b00d5d":{
      "scriptId":"u46"},
    "196f48a3eea1427cac7dcb31aa38c0cf":{
      "scriptId":"u47"},
    "988da03d435a40bcbe6278d7308e0c3b":{
      "scriptId":"u48"},
    "0796f35389b4444d88199b37bf23b2a7":{
      "scriptId":"u49"},
    "a6631d06b16641d590e1ae039f9a5317":{
      "scriptId":"u50"},
    "9f029671a5da4436864e75032e754e25":{
      "scriptId":"u51"},
    "94f80c3adb4842c99e68a0fac359798c":{
      "scriptId":"u52"},
    "45f396b02bf04d3889324774e5f1dcb1":{
      "scriptId":"u53"},
    "07e004c7b3c04cb78e854717c29df993":{
      "scriptId":"u54"},
    "1491aad1b00e4afeb6e6b9f30b9a3938":{
      "scriptId":"u55"},
    "069be61b75324cf9b5722dccd8df6a20":{
      "scriptId":"u56"},
    "976e0358b4c94e6e92e5515276ec4b7f":{
      "scriptId":"u57"},
    "0f9a0f5db24f4680a7b31b03ed23db10":{
      "scriptId":"u58"},
    "0ddbc8aa2ef34404bef27e6c718c8d62":{
      "scriptId":"u59"},
    "6b00fad06c8f4f4cb410c3489ec6bb4f":{
      "scriptId":"u60"},
    "411345f3767e4a0199b8b19956c847a5":{
      "scriptId":"u61"},
    "48c5abfd67cf486792bbdc44d1001f12":{
      "scriptId":"u62"},
    "19ef8d72ef4243f2904d4227fb4d6244":{
      "scriptId":"u63"},
    "1646c159277147c69415c5270d09369d":{
      "scriptId":"u64"},
    "5c30de87357f4c8caf54972f92c2f94b":{
      "scriptId":"u65"},
    "93e44a04c26e4ea2876fd278b8f27f8a":{
      "scriptId":"u66"},
    "6ffe23d646d44e97a09edfebc1e45d22":{
      "scriptId":"u67"},
    "c855801cb6694903b47d182133efb1eb":{
      "scriptId":"u68"},
    "36dfdaf635994ac99b9eb0878af8f935":{
      "scriptId":"u69"},
    "b3513f419881436992a65322254d082b":{
      "scriptId":"u70"},
    "93e980ac3cbc44a98434241dad4ad2cb":{
      "scriptId":"u71"},
    "80126955920b48eba0b008078cfbeeb1":{
      "scriptId":"u72"},
    "8af3acb43ae247ffa473f6ac7312054a":{
      "scriptId":"u73"},
    "d7a4b8c095214f5ab1ded2682f4eb445":{
      "scriptId":"u74"},
    "0b1a436a3d314c19b825eaffbe38aa15":{
      "scriptId":"u75"},
    "64cf40bc3e7248e2a452456cc193e03d":{
      "scriptId":"u76"},
    "ff27a9f3f24343f1a4836870a9b46181":{
      "scriptId":"u77"},
    "646bce2d0f4c4f7a89f7cd8be97680e8":{
      "scriptId":"u78"},
    "9b6bc3334ef74ec59fa43c184cfe4ad2":{
      "scriptId":"u79"},
    "3220bc1064184af282ce89a39af5908d":{
      "scriptId":"u80"},
    "68d9afd944f04acdbf30ddb8f5acfdca":{
      "scriptId":"u81"},
    "aa656fd90d3e4db78cfa114137c88bb5":{
      "scriptId":"u82"},
    "701d2c34b6e5472e911de5f4365e22bc":{
      "scriptId":"u83"},
    "6610ed86212643ab981ab1c4c002cc57":{
      "scriptId":"u84"},
    "76ac7e5f699d4535aaa54042742cada7":{
      "scriptId":"u85"},
    "7df47d4a10374bc19bf574c77f5f600d":{
      "scriptId":"u86"},
    "e2d7bd981a414dd3a5048d4b86624469":{
      "scriptId":"u87"},
    "d5a2a12cb25943509d593c21619efd16":{
      "scriptId":"u88"},
    "f530013f8fd243d18a9a6db7761bd2ee":{
      "scriptId":"u89"},
    "c82dee0519c246aeb123181562fc0dd8":{
      "scriptId":"u90"},
    "39e604f90fb24478a3fd9bf37f07d443":{
      "scriptId":"u91"},
    "437a3cae20d042acb1a78a1a47426bba":{
      "scriptId":"u92"},
    "3c7189054a6d402e968efd6dd474ac5e":{
      "scriptId":"u93"},
    "0c5a92f0a9df45b3bfc3c80a4d3fb20f":{
      "scriptId":"u94"},
    "7110484d235b4f7294fcd406b3d8caeb":{
      "scriptId":"u95"},
    "4c57c3a2292e4c68bdbb71575ff26d0b":{
      "scriptId":"u96"},
    "7afce7e45f124c04987b1acfac9f46f6":{
      "scriptId":"u97"},
    "0756abb329454cf8993fd7f77c73513e":{
      "scriptId":"u98"},
    "91ef90e7f3b64ffd8d19d1d42b308cf5":{
      "scriptId":"u99"},
    "da4f1e98c75e40e8a22d8f397bccc51e":{
      "scriptId":"u100"},
    "9cec653d7e584265a8b0939a35722939":{
      "scriptId":"u101"},
    "0829b845885847128c9c15a24ea2b995":{
      "scriptId":"u102"},
    "7b48842db6084177ae5e4fee8fef70bb":{
      "scriptId":"u103"},
    "fbfd3400929d47f4a58d1889a60226cf":{
      "scriptId":"u104"},
    "c98d9700209e4e679ff7a048d7f0ffe8":{
      "scriptId":"u105"},
    "be53c5be401943c9a13048ebaedcdffc":{
      "scriptId":"u106"},
    "808008dec0a94415a9997e8409fb097b":{
      "scriptId":"u107"},
    "298277f5f9f8491698330ccc6614a633":{
      "scriptId":"u108"},
    "c5388ec6a6a743cbb886bcf147d2de4e":{
      "scriptId":"u109"}}});